# Generated by Django 5.0.1 on 2026-01-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1 ($50/mo)'), ('TIER_2', 'Tier 2 ($100/mo)'), ('TIER_3', 'Tier 3 ($200/mo)')], default='TIER_1', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('trialing', 'Trialing')], default='trialing', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
