# Generated by Django 6.0.1 on 2026-01-27 03:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_paymenthistory_subscriptionchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier name (e.g., FREE, STARTER, PRO, ENTERPRISE)', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown to users', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the tier benefits')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('trainee_limit', models.IntegerField(default=0, help_text='Maximum number of trainees (0 = unlimited)')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this tier')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this tier', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for selection')),
                ('sort_order', models.IntegerField(default=0, help_text='Order in which tiers are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_tiers',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal description', max_length=255)),
                ('coupon_type', models.CharField(choices=[('percent', 'Percentage Discount'), ('fixed', 'Fixed Amount'), ('free_trial', 'Free Trial Days')], default='percent', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (% or $) or number of free trial days', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applies_to', models.CharField(choices=[('trainer', 'Trainer Platform Subscription'), ('trainee', 'Trainee Coaching Subscription'), ('both', 'Both')], default='both', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('exhausted', 'Exhausted')], default='active', max_length=20)),
                ('applicable_tiers', models.JSONField(blank=True, default=list, help_text='List of tier names this coupon applies to (empty = all)')),
                ('max_uses', models.IntegerField(default=0, help_text='Maximum number of times coupon can be used (0 = unlimited)')),
                ('max_uses_per_user', models.IntegerField(default=1, help_text='Maximum uses per user')),
                ('current_uses', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When the coupon becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the coupon expires (null = no expiry)', null=True)),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe Coupon ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, help_text='Admin who created this coupon', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_coupons', to=settings.AUTH_USER_MODEL)),
                ('created_by_trainer', models.ForeignKey(blank=True, help_text='Trainer who created this coupon (null for admin coupons)', limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, help_text='Stripe Connect account ID (acct_...)', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], default='pending', max_length=20)),
                ('charges_enabled', models.BooleanField(default=False, help_text='Whether the account can accept charges')),
                ('payouts_enabled', models.BooleanField(default=False, help_text='Whether the account can receive payouts')),
                ('details_submitted', models.BooleanField(default=False, help_text='Whether account details have been submitted')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether the full onboarding flow is complete')),
                ('default_currency', models.CharField(default='usd', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_accounts',
            },
        ),
        migrations.CreateModel(
            name='TraineePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Monthly Subscription'), ('one_time', 'One-Time Purchase')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee collected on this payment', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraineeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='coaching_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='subscriptions.coupon')),
                ('subscription', models.ForeignKey(blank=True, help_text='Trainer subscription this was applied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
                ('trainee_subscription', models.ForeignKey(blank=True, help_text='Trainee coaching subscription this was applied to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='subscriptions.traineesubscription')),
            ],
            options={
                'db_table': 'coupon_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_subscription_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly coaching subscription price in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monthly_subscription_enabled', models.BooleanField(default=False, help_text='Whether monthly subscriptions are available')),
                ('one_time_consultation_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time consultation price in dollars', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('one_time_consultation_enabled', models.BooleanField(default=False, help_text='Whether one-time consultations are available')),
                ('stripe_monthly_price_id', models.CharField(blank=True, help_text='Stripe Price ID for recurring subscription', max_length=255)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trainer pricing',
                'db_table': 'trainer_pricing',
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status'], name='coupons_status_9a69d0_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_by_trainer'], name='coupons_created_eac9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_until'], name='coupons_valid_u_bf1c18_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeaccount',
            index=models.Index(fields=['trainer'], name='stripe_acco_trainer_d22f35_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeaccount',
            index=models.Index(fields=['status'], name='stripe_acco_status_156e57_idx'),
        ),
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['trainee'], name='trainee_pay_trainee_46fe46_idx'),
        ),
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['trainer'], name='trainee_pay_trainer_29cc67_idx'),
        ),
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['status'], name='trainee_pay_status_493d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['payment_type'], name='trainee_pay_payment_9cbb37_idx'),
        ),
        migrations.AddIndex(
            model_name='traineesubscription',
            index=models.Index(fields=['trainee'], name='trainee_sub_trainee_315c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='traineesubscription',
            index=models.Index(fields=['trainer'], name='trainee_sub_trainer_443925_idx'),
        ),
        migrations.AddIndex(
            model_name='traineesubscription',
            index=models.Index(fields=['status'], name='trainee_sub_status_2e1b1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traineesubscription',
            unique_together={('trainee', 'trainer')},
        ),
    ]
