# Generated by Django 6.0.1 on 2026-02-20 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptiontier_coupon_stripeaccount_traineepayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['paid_at'], name='trainee_pay_paid_at_1371c2_idx'),
        ),
        migrations.AddIndex(
            model_name='traineepayment',
            index=models.Index(fields=['trainer', 'status', 'paid_at'], name='trainee_pay_trainer_c4ed3e_idx'),
        ),
    ]
