# Generated by Django 6.0.1 on 2026-02-23 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_add_paid_at_indexes_to_trainee_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_by_ambassador',
            field=models.ForeignKey(blank=True, help_text='Ambassador who created this coupon', limit_choices_to={'role': 'AMBASSADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['created_by_ambassador'], name='coupons_created_a96829_idx'),
        ),
    ]
