"""
Management command to seed MuscleReference records with curated anatomical data.

Usage:
    python manage.py seed_muscle_references
"""
from __future__ import annotations

from django.core.management.base import BaseCommand

from workouts.models import MuscleReference


MUSCLE_DATA: list[dict] = [
    {
        'slug': 'quads',
        'display_name': 'Quadriceps',
        'latin_name': 'Musculus quadriceps femoris',
        'body_region': 'lower_body',
        'description': 'Large muscle group on the front of the thigh composed of four individual muscles. Primary knee extensors and hip flexors.',
        'origin': 'Rectus femoris: anterior inferior iliac spine. Vastus lateralis: greater trochanter and linea aspera. Vastus medialis: intertrochanteric line and linea aspera. Vastus intermedius: anterior and lateral surfaces of the femoral shaft.',
        'insertion': 'Tibial tuberosity via the patellar tendon.',
        'primary_movements': ['Knee extension', 'Hip flexion (rectus femoris)'],
        'function_description': 'The quadriceps extend the knee during walking, running, jumping, and squatting. The rectus femoris also assists in hip flexion. They are essential for standing up, climbing stairs, and decelerating the body.',
        'training_tips': 'Squats, leg press, and lunges target the full quad complex. Leg extensions isolate the quads. Vary foot placement and squat depth to emphasize different heads.',
        'common_exercises': ['Barbell Back Squat', 'Leg Press', 'Bulgarian Split Squat', 'Leg Extension', 'Front Squat', 'Walking Lunge'],
        'sub_muscles': [
            {'name': 'Rectus Femoris', 'latin_name': 'Musculus rectus femoris', 'description': 'Runs straight down the middle of the thigh; the only quad that crosses the hip joint.'},
            {'name': 'Vastus Lateralis', 'latin_name': 'Musculus vastus lateralis', 'description': 'Largest quad muscle on the outer thigh.'},
            {'name': 'Vastus Medialis', 'latin_name': 'Musculus vastus medialis', 'description': 'Inner thigh quad, important for patellar tracking. The VMO (oblique portion) stabilizes the kneecap.'},
            {'name': 'Vastus Intermedius', 'latin_name': 'Musculus vastus intermedius', 'description': 'Lies beneath the rectus femoris on the front of the femur.'},
        ],
        'sort_order': 1,
    },
    {
        'slug': 'hamstrings',
        'display_name': 'Hamstrings',
        'latin_name': 'Musculi hamstrings (biceps femoris, semitendinosus, semimembranosus)',
        'body_region': 'lower_body',
        'description': 'Group of three muscles on the posterior thigh responsible for knee flexion and hip extension.',
        'origin': 'Ischial tuberosity (all three). Biceps femoris short head: linea aspera of the femur.',
        'insertion': 'Biceps femoris: head of the fibula. Semitendinosus: medial surface of the proximal tibia. Semimembranosus: medial tibial condyle.',
        'primary_movements': ['Knee flexion', 'Hip extension', 'Tibial rotation'],
        'function_description': 'The hamstrings decelerate the lower leg during running, extend the hip during sprinting and deadlifting, and stabilize the knee joint. They work eccentrically during the swing phase of gait.',
        'training_tips': 'Romanian deadlifts and good mornings train hip extension. Leg curls target knee flexion. Nordic curls build eccentric strength for injury prevention.',
        'common_exercises': ['Romanian Deadlift', 'Lying Leg Curl', 'Nordic Hamstring Curl', 'Good Morning', 'Glute-Ham Raise', 'Stiff-Leg Deadlift'],
        'sub_muscles': [
            {'name': 'Biceps Femoris (Long Head)', 'latin_name': 'Musculus biceps femoris caput longum', 'description': 'Lateral hamstring; crosses both hip and knee joints.'},
            {'name': 'Biceps Femoris (Short Head)', 'latin_name': 'Musculus biceps femoris caput breve', 'description': 'Lateral hamstring; only crosses the knee joint.'},
            {'name': 'Semitendinosus', 'latin_name': 'Musculus semitendinosus', 'description': 'Medial hamstring with a long tendon; crosses both joints.'},
            {'name': 'Semimembranosus', 'latin_name': 'Musculus semimembranosus', 'description': 'Deep medial hamstring; crosses both joints.'},
        ],
        'sort_order': 2,
    },
    {
        'slug': 'glutes',
        'display_name': 'Glutes',
        'latin_name': 'Musculi glutei',
        'body_region': 'lower_body',
        'description': 'The three gluteal muscles form the buttocks and are the most powerful hip extensors in the body.',
        'origin': 'Gluteus maximus: posterior gluteal line of the ilium, sacrum, coccyx. Gluteus medius: outer surface of the ilium. Gluteus minimus: outer surface of the ilium (below medius).',
        'insertion': 'Gluteus maximus: gluteal tuberosity of the femur and IT band. Gluteus medius and minimus: greater trochanter of the femur.',
        'primary_movements': ['Hip extension', 'Hip abduction', 'Hip external rotation'],
        'function_description': 'The gluteus maximus is the primary hip extensor, powering movements like standing from a seated position, climbing, and sprinting. The medius and minimus stabilize the pelvis during single-leg stance and walking.',
        'training_tips': 'Hip thrusts and deadlifts emphasize the gluteus maximus. Side-lying abductions and banded walks target the medius and minimus. Full range of motion squats also recruit glutes heavily.',
        'common_exercises': ['Barbell Hip Thrust', 'Deadlift', 'Cable Kickback', 'Step-Up', 'Sumo Squat', 'Glute Bridge'],
        'sub_muscles': [
            {'name': 'Gluteus Maximus', 'latin_name': 'Musculus gluteus maximus', 'description': 'Largest and most superficial gluteal muscle; primary hip extensor.'},
            {'name': 'Gluteus Medius', 'latin_name': 'Musculus gluteus medius', 'description': 'Fan-shaped muscle on the outer pelvis; primary hip abductor.'},
            {'name': 'Gluteus Minimus', 'latin_name': 'Musculus gluteus minimus', 'description': 'Smallest and deepest gluteal muscle; assists in hip abduction and internal rotation.'},
        ],
        'sort_order': 3,
    },
    {
        'slug': 'calves',
        'display_name': 'Calves',
        'latin_name': 'Musculus triceps surae',
        'body_region': 'lower_body',
        'description': 'Muscles of the posterior lower leg responsible for plantar flexion of the ankle.',
        'origin': 'Gastrocnemius: medial and lateral femoral condyles. Soleus: posterior surface of the tibia and fibula.',
        'insertion': 'Calcaneus (heel bone) via the Achilles tendon.',
        'primary_movements': ['Ankle plantar flexion', 'Knee flexion (gastrocnemius)'],
        'function_description': 'The calves push off the ground during walking, running, and jumping. The gastrocnemius provides explosive push-off power while the soleus is a postural muscle important for standing endurance.',
        'training_tips': 'Standing calf raises emphasize the gastrocnemius. Seated calf raises isolate the soleus. Use full range of motion with a pause at the bottom stretch.',
        'common_exercises': ['Standing Calf Raise', 'Seated Calf Raise', 'Donkey Calf Raise', 'Single-Leg Calf Raise', 'Leg Press Calf Raise'],
        'sub_muscles': [
            {'name': 'Gastrocnemius', 'latin_name': 'Musculus gastrocnemius', 'description': 'Two-headed superficial calf muscle that crosses the knee joint.'},
            {'name': 'Soleus', 'latin_name': 'Musculus soleus', 'description': 'Flat muscle beneath the gastrocnemius; does not cross the knee.'},
        ],
        'sort_order': 4,
    },
    {
        'slug': 'hip_adductors',
        'display_name': 'Hip Adductors',
        'latin_name': 'Musculi adductores',
        'body_region': 'lower_body',
        'description': 'Inner thigh muscles that bring the leg toward the midline of the body.',
        'origin': 'Pubic bone and ischium (various points).',
        'insertion': 'Linea aspera and medial epicondyle of the femur (varies by muscle).',
        'primary_movements': ['Hip adduction', 'Hip flexion assist', 'Hip rotation'],
        'function_description': 'The adductors stabilize the pelvis and lower extremity during movement. They assist in hip flexion and play a crucial role in lateral movement control, cutting, and change-of-direction activities.',
        'training_tips': 'Copenhagen planks and adductor machine work target these directly. Sumo squats and wide-stance deadlifts also recruit the adductors heavily.',
        'common_exercises': ['Adductor Machine', 'Copenhagen Plank', 'Sumo Deadlift', 'Wide-Stance Squat', 'Cable Hip Adduction', 'Lateral Lunge'],
        'sub_muscles': [
            {'name': 'Adductor Magnus', 'latin_name': 'Musculus adductor magnus', 'description': 'Largest adductor; has both adduction and hip extension functions.'},
            {'name': 'Adductor Longus', 'latin_name': 'Musculus adductor longus', 'description': 'Superficial adductor on the medial thigh.'},
            {'name': 'Adductor Brevis', 'latin_name': 'Musculus adductor brevis', 'description': 'Short adductor deep to the longus.'},
            {'name': 'Gracilis', 'latin_name': 'Musculus gracilis', 'description': 'Thin, superficial adductor that also crosses the knee joint.'},
            {'name': 'Pectineus', 'latin_name': 'Musculus pectineus', 'description': 'Small muscle at the top of the inner thigh; assists with flexion and adduction.'},
        ],
        'sort_order': 5,
    },
    {
        'slug': 'hip_abductors',
        'display_name': 'Hip Abductors',
        'latin_name': 'Musculi abductores coxae',
        'body_region': 'lower_body',
        'description': 'Muscles on the outer hip that move the leg away from the midline. Crucial for pelvic stability.',
        'origin': 'Outer surface of the ilium (gluteus medius/minimus). TFL: anterior superior iliac spine.',
        'insertion': 'Greater trochanter of the femur (medius/minimus). TFL: IT band to lateral tibial condyle.',
        'primary_movements': ['Hip abduction', 'Pelvic stabilization', 'Hip internal rotation'],
        'function_description': 'The hip abductors prevent the pelvis from dropping during single-leg stance (Trendelenburg sign). They are critical for gait stability, lateral movement, and knee alignment during squats and lunges.',
        'training_tips': 'Side-lying hip abduction, banded walks, and cable abduction target these muscles. Single-leg exercises like pistol squats also demand strong abductor activation.',
        'common_exercises': ['Hip Abduction Machine', 'Banded Lateral Walk', 'Side-Lying Hip Abduction', 'Cable Hip Abduction', 'Clamshell'],
        'sub_muscles': [
            {'name': 'Gluteus Medius', 'latin_name': 'Musculus gluteus medius', 'description': 'Primary hip abductor; also listed under glutes.'},
            {'name': 'Gluteus Minimus', 'latin_name': 'Musculus gluteus minimus', 'description': 'Deep hip abductor assisting the medius.'},
            {'name': 'Tensor Fasciae Latae', 'latin_name': 'Musculus tensor fasciae latae', 'description': 'Small muscle on the anterior-lateral hip that tenses the IT band.'},
        ],
        'sort_order': 6,
    },
    {
        'slug': 'hip_flexors',
        'display_name': 'Hip Flexors',
        'latin_name': 'Musculi flexores coxae',
        'body_region': 'lower_body',
        'description': 'Muscles at the front of the hip that flex the hip joint, bringing the thigh toward the torso.',
        'origin': 'Iliacus: iliac fossa. Psoas major: T12-L5 vertebral bodies. Rectus femoris: AIIS.',
        'insertion': 'Iliacus and psoas: lesser trochanter of the femur. Rectus femoris: tibial tuberosity via patellar tendon.',
        'primary_movements': ['Hip flexion', 'Trunk flexion on the femur', 'Anterior pelvic tilt'],
        'function_description': 'The hip flexors lift the thigh during walking, running, and kicking. The iliopsoas is the strongest hip flexor and plays a role in posture and spinal stabilization. Tight hip flexors can contribute to lower back pain.',
        'training_tips': 'Hanging leg raises and cable hip flexion strengthen these muscles. Stretching and mobility work are equally important due to tightness from prolonged sitting.',
        'common_exercises': ['Hanging Leg Raise', 'Cable Hip Flexion', 'Psoas March', 'Mountain Climbers', 'Decline Sit-Up'],
        'sub_muscles': [
            {'name': 'Iliacus', 'latin_name': 'Musculus iliacus', 'description': 'Flat, triangular muscle filling the iliac fossa.'},
            {'name': 'Psoas Major', 'latin_name': 'Musculus psoas major', 'description': 'Long muscle connecting the lumbar spine to the femur.'},
            {'name': 'Rectus Femoris', 'latin_name': 'Musculus rectus femoris', 'description': 'Quad muscle that also crosses the hip; assists in hip flexion.'},
        ],
        'sort_order': 7,
    },
    {
        'slug': 'spinal_erectors',
        'display_name': 'Spinal Erectors',
        'latin_name': 'Musculus erector spinae',
        'body_region': 'core',
        'description': 'Long muscles running along the spine that extend and stabilize the vertebral column.',
        'origin': 'Sacrum, iliac crest, spinous processes of lumbar and lower thoracic vertebrae.',
        'insertion': 'Spinous and transverse processes of vertebrae, ribs, and the mastoid process of the skull.',
        'primary_movements': ['Spinal extension', 'Lateral flexion', 'Spinal rotation'],
        'function_description': 'The erector spinae maintain an upright posture and extend the spine from a flexed position. They eccentrically control trunk flexion (e.g., lowering into a deadlift) and are critical for maintaining neutral spine during loaded movements.',
        'training_tips': 'Back extensions, deadlifts, and good mornings strengthen the erectors. Avoid excessive rounding under load. Build endurance and strength progressively.',
        'common_exercises': ['Back Extension', 'Deadlift', 'Good Morning', 'Reverse Hyper', 'Bird Dog'],
        'sub_muscles': [
            {'name': 'Iliocostalis', 'latin_name': 'Musculus iliocostalis', 'description': 'Lateral column of the erector spinae; attaches to ribs.'},
            {'name': 'Longissimus', 'latin_name': 'Musculus longissimus', 'description': 'Intermediate column; longest of the erector spinae muscles.'},
            {'name': 'Spinalis', 'latin_name': 'Musculus spinalis', 'description': 'Medial column; attaches to spinous processes.'},
        ],
        'sort_order': 8,
    },
    {
        'slug': 'lats',
        'display_name': 'Latissimus Dorsi',
        'latin_name': 'Musculus latissimus dorsi',
        'body_region': 'upper_body',
        'description': 'Large, flat muscle of the back that gives the torso its V-taper appearance. The widest muscle in the human body.',
        'origin': 'Spinous processes of T7-L5, thoracolumbar fascia, iliac crest, inferior angle of the scapula, and lower 3-4 ribs.',
        'insertion': 'Floor of the intertubercular groove (bicipital groove) of the humerus.',
        'primary_movements': ['Shoulder adduction', 'Shoulder extension', 'Shoulder internal rotation', 'Scapular depression'],
        'function_description': 'The lats are the primary pulling muscles of the upper body. They power movements like pull-ups, rows, and swimming strokes. They also assist in breathing as an accessory respiratory muscle.',
        'training_tips': 'Pull-ups and lat pulldowns build width. Rows build thickness. Focus on scapular depression and retraction to maximize lat engagement. Use a variety of grips.',
        'common_exercises': ['Pull-Up', 'Lat Pulldown', 'Barbell Row', 'Single-Arm Dumbbell Row', 'Seated Cable Row', 'Straight-Arm Pulldown'],
        'sub_muscles': [
            {'name': 'Upper Fibers', 'latin_name': '', 'description': 'Upper portion contributing to shoulder adduction.'},
            {'name': 'Lower Fibers', 'latin_name': '', 'description': 'Lower portion contributing to shoulder extension and the V-taper.'},
        ],
        'sort_order': 9,
    },
    {
        'slug': 'mid_back',
        'display_name': 'Mid Back (Rhomboids & Mid Traps)',
        'latin_name': 'Musculi rhomboidei et trapezius pars media',
        'body_region': 'upper_body',
        'description': 'Muscles between the shoulder blades responsible for scapular retraction and stability.',
        'origin': 'Rhomboids: spinous processes of C7-T5. Mid traps: spinous processes of T1-T5.',
        'insertion': 'Rhomboids: medial border of the scapula. Mid traps: acromion and spine of the scapula.',
        'primary_movements': ['Scapular retraction', 'Scapular stabilization', 'Scapular elevation (rhomboids)'],
        'function_description': 'These muscles pull the shoulder blades together and maintain proper scapular positioning. They counterbalance the anterior pull of the chest and front deltoids, making them essential for posture.',
        'training_tips': 'Face pulls and reverse flyes target these muscles directly. Squeeze the shoulder blades together at the peak contraction. Rowing movements with a pause at the chest also work well.',
        'common_exercises': ['Face Pull', 'Cable Reverse Fly', 'Seated Cable Row (wide grip)', 'Prone Y-Raise', 'Band Pull-Apart', 'Chest-Supported Row'],
        'sub_muscles': [
            {'name': 'Rhomboid Major', 'latin_name': 'Musculus rhomboideus major', 'description': 'Larger rhomboid beneath the trapezius.'},
            {'name': 'Rhomboid Minor', 'latin_name': 'Musculus rhomboideus minor', 'description': 'Smaller rhomboid superior to the major.'},
            {'name': 'Middle Trapezius', 'latin_name': 'Trapezius pars media', 'description': 'Horizontal fibers of the trapezius that retract the scapula.'},
        ],
        'sort_order': 10,
    },
    {
        'slug': 'upper_traps',
        'display_name': 'Upper Trapezius',
        'latin_name': 'Trapezius pars descendens',
        'body_region': 'upper_body',
        'description': 'Upper portion of the trapezius muscle running from the skull and cervical spine to the clavicle and scapula.',
        'origin': 'External occipital protuberance, nuchal ligament, spinous processes of C1-C7.',
        'insertion': 'Lateral third of the clavicle and acromion process of the scapula.',
        'primary_movements': ['Scapular elevation', 'Scapular upward rotation', 'Cervical extension', 'Lateral cervical flexion'],
        'function_description': 'The upper traps elevate the shoulder girdle (shrugging) and assist in upward rotation of the scapula during overhead movements. They also support the head and neck posture.',
        'training_tips': 'Barbell and dumbbell shrugs directly target the upper traps. Farmer carries and overhead pressing also provide significant stimulus. Avoid excessive forward head posture during shrugs.',
        'common_exercises': ['Barbell Shrug', 'Dumbbell Shrug', "Farmer's Carry", 'Overhead Press', 'Upright Row', 'Trap Bar Shrug'],
        'sub_muscles': [],
        'sort_order': 11,
    },
    {
        'slug': 'rear_delts',
        'display_name': 'Rear Deltoids',
        'latin_name': 'Deltoideus pars spinalis',
        'body_region': 'upper_body',
        'description': 'Posterior head of the deltoid muscle responsible for shoulder extension and external rotation.',
        'origin': 'Spine of the scapula.',
        'insertion': 'Deltoid tuberosity of the humerus.',
        'primary_movements': ['Shoulder horizontal abduction', 'Shoulder extension', 'Shoulder external rotation'],
        'function_description': 'The rear deltoids pull the arm backward and outward. They are crucial for balanced shoulder development, posture, and injury prevention. They work synergistically with the mid back during rowing movements.',
        'training_tips': 'Reverse flyes, face pulls, and rear delt flyes on the pec deck target this muscle. Higher rep ranges (15-25) often work well. Ensure equal volume with front delts for shoulder health.',
        'common_exercises': ['Reverse Pec Deck Fly', 'Face Pull', 'Bent-Over Reverse Fly', 'Cable Rear Delt Fly', 'Band Pull-Apart'],
        'sub_muscles': [],
        'sort_order': 12,
    },
    {
        'slug': 'side_delts',
        'display_name': 'Lateral Deltoids',
        'latin_name': 'Deltoideus pars acromialis',
        'body_region': 'upper_body',
        'description': 'Middle head of the deltoid responsible for shoulder abduction, creating shoulder width.',
        'origin': 'Acromion process of the scapula.',
        'insertion': 'Deltoid tuberosity of the humerus.',
        'primary_movements': ['Shoulder abduction', 'Shoulder flexion assist'],
        'function_description': 'The lateral deltoids lift the arm out to the side and are the primary contributor to shoulder width and the "capped" shoulder appearance. They initiate abduction after the supraspinatus.',
        'training_tips': 'Lateral raises are the most targeted exercise. Use controlled tempo and avoid excessive momentum. Cable lateral raises maintain constant tension throughout the range of motion.',
        'common_exercises': ['Dumbbell Lateral Raise', 'Cable Lateral Raise', 'Machine Lateral Raise', 'Overhead Press', 'Upright Row'],
        'sub_muscles': [],
        'sort_order': 13,
    },
    {
        'slug': 'front_delts',
        'display_name': 'Front Deltoids',
        'latin_name': 'Deltoideus pars clavicularis',
        'body_region': 'upper_body',
        'description': 'Anterior head of the deltoid responsible for shoulder flexion and internal rotation.',
        'origin': 'Lateral third of the clavicle.',
        'insertion': 'Deltoid tuberosity of the humerus.',
        'primary_movements': ['Shoulder flexion', 'Shoulder horizontal adduction', 'Shoulder internal rotation'],
        'function_description': 'The front deltoids raise the arm forward and assist in pressing movements. They are heavily involved in bench pressing, overhead pressing, and front raises. Often overdeveloped relative to rear delts in typical training programs.',
        'training_tips': 'Overhead presses and front raises target the anterior delt directly. Most lifters get sufficient front delt work from pressing movements. Avoid overtraining relative to rear delts.',
        'common_exercises': ['Overhead Press', 'Front Raise', 'Arnold Press', 'Incline Bench Press', 'Landmine Press'],
        'sub_muscles': [],
        'sort_order': 14,
    },
    {
        'slug': 'chest',
        'display_name': 'Chest',
        'latin_name': 'Musculus pectoralis major',
        'body_region': 'upper_body',
        'description': 'Large, fan-shaped muscle of the anterior chest wall. Primary horizontal pressing muscle.',
        'origin': 'Clavicular head: medial half of the clavicle. Sternal head: sternum, upper 6 costal cartilages. Abdominal head: aponeurosis of the external oblique.',
        'insertion': 'Lateral lip of the intertubercular groove (bicipital groove) of the humerus.',
        'primary_movements': ['Shoulder horizontal adduction', 'Shoulder flexion (clavicular head)', 'Shoulder internal rotation', 'Shoulder adduction'],
        'function_description': 'The pectoralis major adducts and internally rotates the humerus. It powers pushing and hugging motions. The clavicular (upper) head assists in shoulder flexion while the sternal (lower) head assists in shoulder extension from a flexed position.',
        'training_tips': 'Incline pressing targets the upper (clavicular) chest. Flat pressing targets the sternal head. Dips and decline pressing emphasize the lower fibers. Flyes isolate the chest with less tricep involvement.',
        'common_exercises': ['Barbell Bench Press', 'Incline Dumbbell Press', 'Dumbbell Fly', 'Cable Crossover', 'Push-Up', 'Dip'],
        'sub_muscles': [
            {'name': 'Clavicular Head (Upper Chest)', 'latin_name': 'Pectoralis major pars clavicularis', 'description': 'Upper fibers originating from the clavicle; targeted by incline movements.'},
            {'name': 'Sternal Head (Mid Chest)', 'latin_name': 'Pectoralis major pars sternocostalis', 'description': 'Largest portion from the sternum and ribs; targeted by flat pressing.'},
            {'name': 'Abdominal Head (Lower Chest)', 'latin_name': 'Pectoralis major pars abdominalis', 'description': 'Lower fibers targeted by decline pressing and dips.'},
        ],
        'sort_order': 15,
    },
    {
        'slug': 'triceps',
        'display_name': 'Triceps',
        'latin_name': 'Musculus triceps brachii',
        'body_region': 'upper_body',
        'description': 'Three-headed muscle on the posterior upper arm. Primary elbow extensor and the largest arm muscle.',
        'origin': 'Long head: infraglenoid tubercle of the scapula. Lateral head: posterior surface of the humerus (above radial groove). Medial head: posterior surface of the humerus (below radial groove).',
        'insertion': 'Olecranon process of the ulna.',
        'primary_movements': ['Elbow extension', 'Shoulder extension (long head)'],
        'function_description': 'The triceps extend the elbow in all pressing movements. The long head also assists in shoulder extension and adduction. The triceps make up roughly two-thirds of upper arm mass.',
        'training_tips': 'Close-grip bench press and dips build overall mass. Overhead tricep extensions stretch the long head. Pushdowns target the lateral and medial heads. Vary the angle and grip for complete development.',
        'common_exercises': ['Tricep Pushdown', 'Close-Grip Bench Press', 'Overhead Tricep Extension', 'Skull Crusher', 'Dip', 'Diamond Push-Up'],
        'sub_muscles': [
            {'name': 'Long Head', 'latin_name': 'Caput longum', 'description': 'Only head crossing the shoulder joint; largest of the three.'},
            {'name': 'Lateral Head', 'latin_name': 'Caput laterale', 'description': 'Outer head creating the horseshoe shape.'},
            {'name': 'Medial Head', 'latin_name': 'Caput mediale', 'description': 'Deep head active in all elbow extension movements.'},
        ],
        'sort_order': 16,
    },
    {
        'slug': 'biceps',
        'display_name': 'Biceps',
        'latin_name': 'Musculus biceps brachii',
        'body_region': 'upper_body',
        'description': 'Two-headed muscle on the anterior upper arm. Primary elbow flexor and forearm supinator.',
        'origin': 'Long head: supraglenoid tubercle of the scapula. Short head: coracoid process of the scapula.',
        'insertion': 'Radial tuberosity and bicipital aponeurosis into the deep fascia of the forearm.',
        'primary_movements': ['Elbow flexion', 'Forearm supination', 'Shoulder flexion assist'],
        'function_description': 'The biceps flex the elbow and supinate the forearm (turning the palm up). The long head assists in shoulder flexion and stabilization. They are most active when the forearm is supinated.',
        'training_tips': 'Supinated (underhand) grip curls maximize biceps activation. Incline curls stretch the long head. Concentration curls isolate the short head. Include both supinated and neutral grip work.',
        'common_exercises': ['Barbell Curl', 'Dumbbell Curl', 'Incline Dumbbell Curl', 'Preacher Curl', 'Hammer Curl', 'Cable Curl'],
        'sub_muscles': [
            {'name': 'Long Head', 'latin_name': 'Caput longum', 'description': 'Outer head forming the biceps peak; crosses the shoulder joint.'},
            {'name': 'Short Head', 'latin_name': 'Caput breve', 'description': 'Inner head contributing to biceps width.'},
        ],
        'sort_order': 17,
    },
    {
        'slug': 'forearms_and_grip',
        'display_name': 'Forearms & Grip',
        'latin_name': 'Musculi antebrachii',
        'body_region': 'upper_body',
        'description': 'Complex group of muscles in the forearm controlling wrist movement, finger flexion/extension, and grip strength.',
        'origin': 'Flexors: medial epicondyle of the humerus. Extensors: lateral epicondyle of the humerus. Brachioradialis: lateral supracondylar ridge.',
        'insertion': 'Various: metacarpals, phalanges, radius, and ulna.',
        'primary_movements': ['Wrist flexion', 'Wrist extension', 'Grip (finger flexion)', 'Forearm pronation/supination'],
        'function_description': 'The forearm muscles control all hand and wrist movements. Grip strength is fundamental to pulling exercises, carrying, and daily activities. The brachioradialis is a powerful elbow flexor in the neutral grip position.',
        'training_tips': 'Wrist curls and reverse wrist curls build forearm size. Farmer carries and dead hangs build grip endurance. Avoid always using straps to let grip develop naturally.',
        'common_exercises': ['Wrist Curl', 'Reverse Wrist Curl', "Farmer's Carry", 'Dead Hang', 'Plate Pinch', 'Hammer Curl', 'Reverse Curl'],
        'sub_muscles': [
            {'name': 'Wrist Flexors', 'latin_name': 'Musculi flexores carpi', 'description': 'Group of muscles on the inner forearm that flex the wrist.'},
            {'name': 'Wrist Extensors', 'latin_name': 'Musculi extensores carpi', 'description': 'Group of muscles on the outer forearm that extend the wrist.'},
            {'name': 'Brachioradialis', 'latin_name': 'Musculus brachioradialis', 'description': 'Large forearm muscle that flexes the elbow in neutral grip.'},
            {'name': 'Finger Flexors', 'latin_name': 'Musculi flexores digitorum', 'description': 'Deep muscles controlling grip and finger curling.'},
        ],
        'sort_order': 18,
    },
    {
        'slug': 'abs_rectus',
        'display_name': 'Rectus Abdominis',
        'latin_name': 'Musculus rectus abdominis',
        'body_region': 'core',
        'description': 'The "six-pack" muscle running vertically along the front of the abdomen, divided by tendinous intersections.',
        'origin': 'Pubic crest and pubic symphysis.',
        'insertion': 'Xiphoid process and costal cartilages of ribs 5-7.',
        'primary_movements': ['Trunk flexion', 'Posterior pelvic tilt', 'Compression of abdominal contents'],
        'function_description': 'The rectus abdominis flexes the trunk (bringing the ribcage toward the pelvis) and stabilizes the core during compound movements. It also plays a role in forced exhalation and increasing intra-abdominal pressure.',
        'training_tips': 'Crunches and sit-ups target the upper portion. Reverse crunches and leg raises emphasize the lower portion. Cable crunches allow progressive overload. Maintain a posterior pelvic tilt to maximize activation.',
        'common_exercises': ['Cable Crunch', 'Hanging Leg Raise', 'Ab Rollout', 'Crunch', 'Reverse Crunch', 'V-Up'],
        'sub_muscles': [
            {'name': 'Upper Rectus Abdominis', 'latin_name': '', 'description': 'Upper segments targeted by crunching movements.'},
            {'name': 'Lower Rectus Abdominis', 'latin_name': '', 'description': 'Lower segments targeted by reverse crunches and leg raises.'},
        ],
        'sort_order': 19,
    },
    {
        'slug': 'obliques',
        'display_name': 'Obliques',
        'latin_name': 'Musculi obliqui abdominis',
        'body_region': 'core',
        'description': 'Muscles on the sides of the abdomen responsible for trunk rotation and lateral flexion.',
        'origin': 'External oblique: outer surfaces of ribs 5-12. Internal oblique: thoracolumbar fascia, iliac crest, inguinal ligament.',
        'insertion': 'External oblique: linea alba, pubic tubercle, anterior iliac crest. Internal oblique: linea alba, pubic crest, ribs 10-12.',
        'primary_movements': ['Trunk rotation', 'Lateral flexion', 'Trunk flexion assist', 'Compression of abdominal contents'],
        'function_description': 'The obliques rotate and laterally flex the trunk. The external oblique on one side works with the internal oblique on the opposite side during rotation. They provide lateral core stability and contribute to the waist aesthetic.',
        'training_tips': 'Russian twists, Pallof presses, and woodchops train rotation. Side planks train anti-lateral flexion. Avoid excessive direct oblique work if waist thickening is a concern.',
        'common_exercises': ['Russian Twist', 'Pallof Press', 'Woodchop', 'Side Plank', 'Bicycle Crunch', 'Hanging Oblique Raise'],
        'sub_muscles': [
            {'name': 'External Oblique', 'latin_name': 'Musculus obliquus externus abdominis', 'description': 'Superficial oblique with fibers running diagonally downward.'},
            {'name': 'Internal Oblique', 'latin_name': 'Musculus obliquus internus abdominis', 'description': 'Deep oblique with fibers running diagonally upward, perpendicular to the external.'},
        ],
        'sort_order': 20,
    },
    {
        'slug': 'deep_core',
        'display_name': 'Deep Core',
        'latin_name': 'Musculi stabilizatores trunci profundi',
        'body_region': 'core',
        'description': 'Deep stabilizing muscles of the trunk including the transverse abdominis, multifidus, pelvic floor, and diaphragm.',
        'origin': 'Transverse abdominis: iliac crest, inguinal ligament, thoracolumbar fascia, costal cartilages of ribs 7-12. Multifidus: sacrum, iliac crest, transverse processes of vertebrae.',
        'insertion': 'Transverse abdominis: linea alba, pubic crest. Multifidus: spinous processes of vertebrae 2-4 levels above origin.',
        'primary_movements': ['Core stabilization', 'Intra-abdominal pressure regulation', 'Spinal segmental stability'],
        'function_description': 'The deep core muscles create a natural "corset" that stabilizes the spine and pelvis. The transverse abdominis activates before any limb movement to brace the spine. The multifidus provides segmental spinal stability. These muscles are foundational for all loaded movements.',
        'training_tips': 'Dead bugs, bird dogs, and Pallof presses train deep core stability. Focus on bracing rather than flexion. Breathing drills and diaphragmatic breathing improve activation. These muscles respond well to isometric and anti-movement exercises.',
        'common_exercises': ['Dead Bug', 'Bird Dog', 'Pallof Press', 'Plank', 'Hollow Body Hold', 'Diaphragmatic Breathing'],
        'sub_muscles': [
            {'name': 'Transverse Abdominis', 'latin_name': 'Musculus transversus abdominis', 'description': 'Deepest abdominal muscle wrapping horizontally around the trunk like a corset.'},
            {'name': 'Multifidus', 'latin_name': 'Musculus multifidus', 'description': 'Small, deep spinal muscles providing segmental stability.'},
            {'name': 'Pelvic Floor', 'latin_name': 'Musculi diaphragma pelvis', 'description': 'Muscles forming the base of the core cylinder; support pelvic organs.'},
            {'name': 'Diaphragm', 'latin_name': 'Musculus diaphragma', 'description': 'Primary breathing muscle forming the top of the core cylinder.'},
        ],
        'sort_order': 21,
    },
]


class Command(BaseCommand):
    help = 'Seed MuscleReference records with curated anatomical data for all 21 detailed muscle groups.'

    def handle(self, *args: object, **options: object) -> None:
        created_count = 0
        updated_count = 0

        for data in MUSCLE_DATA:
            slug = data['slug']
            defaults = {k: v for k, v in data.items() if k != 'slug'}
            _, created = MuscleReference.objects.update_or_create(
                slug=slug,
                defaults=defaults,
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Done: {created_count} created, {updated_count} updated. '
                f'Total: {MuscleReference.objects.count()} muscle references.'
            )
        )
