# Generated by Django 6.0.1 on 2026-01-30 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Calendar'), ('microsoft', 'Microsoft Outlook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Authorization'), ('connected', 'Connected'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Connection Error')], default='pending', max_length=20)),
                ('_access_token', models.TextField(blank=True, db_column='access_token')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('calendar_id', models.CharField(blank=True, max_length=255)),
                ('calendar_email', models.EmailField(blank=True, max_length=254)),
                ('calendar_name', models.CharField(blank=True, max_length=255)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_link', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('event_type', models.CharField(choices=[('session', 'Training Session'), ('availability', 'Available Slot'), ('blocked', 'Blocked Time'), ('external', 'External Event')], default='external', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendarconnection')),
                ('trainee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('connection', 'external_id')},
            },
        ),
    ]
