# Generated by Django 6.0.1 on 2026-01-26 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0003_programtemplate_programweek_weeklynutritionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workouts_completed', models.PositiveIntegerField(default=0)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('total_volume', models.FloatField(default=0, help_text='Total weight x reps in kg')),
                ('calories_consumed', models.PositiveIntegerField(default=0)),
                ('protein_consumed', models.PositiveIntegerField(default=0)),
                ('carbs_consumed', models.PositiveIntegerField(default=0)),
                ('fat_consumed', models.PositiveIntegerField(default=0)),
                ('logged_food', models.BooleanField(default=False)),
                ('logged_workout', models.BooleanField(default=False)),
                ('hit_protein_goal', models.BooleanField(default=False)),
                ('hit_calorie_goal', models.BooleanField(default=False)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee_activity_summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trainee', 'date'], name='trainee_act_trainee_3a50b8_idx'), models.Index(fields=['date'], name='trainee_act_date_b5f276_idx')],
                'unique_together': {('trainee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TraineeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invitation_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Personal message from trainer to include in invitation')),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_template', models.ForeignKey(blank=True, help_text='Optional program template to assign upon acceptance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.programtemplate')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee_invitations',
                'indexes': [models.Index(fields=['invitation_code'], name='trainee_inv_invitat_931254_idx'), models.Index(fields=['email'], name='trainee_inv_email_5f1e04_idx'), models.Index(fields=['trainer', 'status'], name='trainee_inv_trainer_955d9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actions_log', models.JSONField(default=list)),
                ('is_read_only', models.BooleanField(default=True, help_text='If True, trainer can only view data. If False, can make changes.')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_sessions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['trainer'], name='trainer_ses_trainer_e4225a_idx'), models.Index(fields=['trainee'], name='trainer_ses_trainee_51c738_idx'), models.Index(fields=['started_at'], name='trainer_ses_started_7c57e6_idx')],
            },
        ),
    ]
