# Generated by Django 6.0.1 on 2026-02-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('trainee_readiness', 'Trainee Readiness'), ('workout_completed', 'Workout Completed'), ('workout_missed', 'Workout Missed'), ('goal_hit', 'Goal Hit'), ('check_in', 'Check In'), ('message', 'Message'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional data associated with the notification')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainer', 'is_read'], name='trainer_not_trainer_0e616c_idx'), models.Index(fields=['trainer', 'created_at'], name='trainer_not_trainer_3a73e5_idx'), models.Index(fields=['notification_type'], name='trainer_not_notific_4e4402_idx')],
            },
        ),
    ]
