# Generated by Django 6.0.1 on 2026-02-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_add_trainer_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('classic', 'Classic'), ('card', 'Card'), ('minimal', 'Minimal')], default='classic', help_text='Which workout UI the trainee sees: classic (table), card (swipe), minimal (list)', max_length=20)),
                ('config_options', models.JSONField(blank=True, default=dict, help_text='Future per-layout settings (show_previous, auto_rest_timer, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_layouts', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.OneToOneField(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='workout_layout_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_layout_configs',
                'indexes': [models.Index(fields=['trainee'], name='workout_lay_trainee_6a9e12_idx')],
            },
        ),
    ]
