# Generated by Django 6.0.1 on 2026-02-14 17:09

import trainer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_add_trainer_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainernotification',
            name='trainer_not_trainer_3a73e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainernotification',
            name='trainer_not_notific_4e4402_idx',
        ),
        migrations.AlterField(
            model_name='trainerbranding',
            name='logo',
            field=models.ImageField(blank=True, help_text='Trainer logo image (JPEG/PNG/WebP, max 2MB, 128x128 to 1024x1024)', null=True, upload_to=trainer.models._branding_logo_upload_path),
        ),
        migrations.AddIndex(
            model_name='trainernotification',
            index=models.Index(fields=['trainer', '-created_at'], name='trainer_not_trainer_3df9be_idx'),
        ),
    ]
