# Generated by Django 6.0.1 on 2026-02-24 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_trainernotification_trainer_not_trainer_3a73e5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New conversation', max_length=200)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee_context', models.ForeignKey(blank=True, help_text='Optional trainee to scope AI context to', limit_choices_to={'role': 'TRAINEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_context_threads', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('usage_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trainer.aichatthread')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aichatthread',
            index=models.Index(fields=['trainer', '-last_message_at'], name='ai_chat_thr_trainer_5964e0_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatthread',
            index=models.Index(fields=['trainer', 'is_deleted'], name='ai_chat_thr_trainer_f559fc_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='ai_chat_mes_thread__8aa1fb_idx'),
        ),
    ]
