# Generated by Django 6.0.1 on 2026-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_ai_chat_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainernotification',
            name='notification_type',
            field=models.CharField(choices=[('trainee_readiness', 'Trainee Readiness'), ('workout_completed', 'Workout Completed'), ('workout_missed', 'Workout Missed'), ('goal_hit', 'Goal Hit'), ('check_in', 'Check In'), ('message', 'Message'), ('churn_alert', 'Churn Alert'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
