# Generated by Django 6.0.1 on 2026-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_alter_trainernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlayoutconfig',
            name='layout_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('card', 'Card'), ('minimal', 'Minimal'), ('video', 'Video')], default='classic', help_text='Which workout UI the trainee sees: classic (table), card (swipe), minimal (list), video (demo videos)', max_length=20),
        ),
    ]
