# Generated by Django 6.0.1 on 2026-03-10 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_workoutlayoutconfig_layout_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email Only'), ('both', 'Both'), ('disabled', 'Disabled')], default='in_app', max_length=20)),
                ('delivery_hour', models.PositiveSmallIntegerField(default=7, help_text="Hour of day (0-23) to deliver digest in trainer's timezone.")),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('include_nutrition', models.BooleanField(default=True)),
                ('include_workouts', models.BooleanField(default=True)),
                ('include_pain_reports', models.BooleanField(default=True)),
                ('include_at_risk', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='digest_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digest_preferences',
            },
        ),
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date this digest summarizes.')),
                ('total_trainees', models.PositiveIntegerField(default=0)),
                ('active_trainees', models.PositiveIntegerField(default=0, help_text='Trainees who logged anything today.')),
                ('workouts_completed', models.PositiveIntegerField(default=0)),
                ('workouts_missed', models.PositiveIntegerField(default=0)),
                ('pain_reports', models.PositiveIntegerField(default=0)),
                ('avg_compliance_pct', models.FloatField(default=0.0, help_text='Average nutrition compliance across trainees (0-100).')),
                ('summary_text', models.TextField(blank=True, default='', help_text='AI-generated narrative summary of the day.')),
                ('highlights', models.JSONField(default=list, help_text='List of notable events: PRs, streaks, milestones.')),
                ('concerns', models.JSONField(default=list, help_text='List of concerns: missed sessions, pain reports, drops.')),
                ('action_items', models.JSONField(default=list, help_text='Suggested actions for the trainer.')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_digests',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trainer', '-date'], name='daily_diges_trainer_2141ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'date'), name='unique_digest_per_trainer_per_date')],
            },
        ),
    ]
