# Generated by Django 6.0.1 on 2026-01-26 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('trainer_tools', 'Trainer Tools'), ('trainee_app', 'Trainee App'), ('nutrition', 'Nutrition'), ('workouts', 'Workouts'), ('analytics', 'Analytics'), ('integrations', 'Integrations'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('planned', 'Planned'), ('in_development', 'In Development'), ('released', 'Released'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes visible to admins only')),
                ('public_response', models.TextField(blank=True, help_text='Public response from team')),
                ('target_release', models.CharField(blank=True, help_text='Target release version or quarter', max_length=50)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_requests',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_admin_response', models.BooleanField(default=False, help_text='True if this is an official response from the team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_comments', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='features.featurerequest')),
            ],
            options={
                'db_table': 'feature_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='features.featurerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_votes',
            },
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['status'], name='feature_req_status_bfa2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['category'], name='feature_req_categor_a77595_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['submitted_by'], name='feature_req_submitt_71c90b_idx'),
        ),
        migrations.AddIndex(
            model_name='featurerequest',
            index=models.Index(fields=['-upvotes', '-created_at'], name='feature_req_upvotes_9e7a53_idx'),
        ),
        migrations.AddIndex(
            model_name='featurecomment',
            index=models.Index(fields=['feature', 'created_at'], name='feature_com_feature_908512_idx'),
        ),
        migrations.AddIndex(
            model_name='featurevote',
            index=models.Index(fields=['feature', 'vote_type'], name='feature_vot_feature_53cf14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featurevote',
            unique_together={('feature', 'user')},
        ),
    ]
