# Generated by Django 5.0.1 on 2026-01-24 06:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nutrition_data', models.JSONField(blank=True, default=dict, help_text='Nutrition log entries parsed from natural language')),
                ('workout_data', models.JSONField(blank=True, default=dict, help_text='Workout log entries parsed from natural language')),
                ('steps', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('sleep_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)])),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('recovery_score', models.IntegerField(blank=True, help_text='Calculated recovery score based on sleep, HR, and activity', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trainee', 'date'], name='daily_logs_trainee_1cdee9_idx'), models.Index(fields=['date'], name='daily_logs_date_f73777_idx')],
                'unique_together': {('trainee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], default='other', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='True for system defaults, False for trainer custom exercises')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer who created this exercise (null for public/system exercises)', limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises',
                'indexes': [models.Index(fields=['muscle_group'], name='exercises_muscle__f519d0_idx'), models.Index(fields=['is_public'], name='exercises_is_publ_50d1b5_idx'), models.Index(fields=['created_by'], name='exercises_created_eae801_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.JSONField(default=dict, help_text='Structured program schedule with weeks and days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Trainer who created this program', limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee'], name='programs_trainee_924f76_idx'), models.Index(fields=['is_active'], name='programs_is_acti_0a53dc_idx'), models.Index(fields=['start_date', 'end_date'], name='programs_start_d_976bd0_idx')],
            },
        ),
    ]
