# Generated by Django 5.0.1 on 2026-01-26 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_goal', models.PositiveIntegerField(default=0, help_text='Daily protein goal in grams')),
                ('carbs_goal', models.PositiveIntegerField(default=0, help_text='Daily carbohydrate goal in grams')),
                ('fat_goal', models.PositiveIntegerField(default=0, help_text='Daily fat goal in grams')),
                ('calories_goal', models.PositiveIntegerField(default=0, help_text='Daily calorie goal')),
                ('per_meal_protein', models.PositiveIntegerField(default=0)),
                ('per_meal_carbs', models.PositiveIntegerField(default=0)),
                ('per_meal_fat', models.PositiveIntegerField(default=0)),
                ('is_trainer_adjusted', models.BooleanField(default=False, help_text='True if a trainer has manually adjusted these goals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_nutrition_goals', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.OneToOneField(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_goals',
            },
        ),
        migrations.CreateModel(
            name='WeightCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(500.0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='weight_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_checkins',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['trainee', 'date'], name='weight_chec_trainee_5e2998_idx')],
                'unique_together': {('trainee', 'date')},
            },
        ),
    ]
