# Generated by Django 6.0.1 on 2026-01-26 03:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_nutritiongoal_weightcheckin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(help_text='Program duration in weeks', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('schedule_template', models.JSONField(default=dict, help_text='Weekly workout schedule template')),
                ('nutrition_template', models.JSONField(default=dict, help_text='Base nutrition guidelines and macro ratios')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('goal_type', models.CharField(choices=[('build_muscle', 'Build Muscle'), ('fat_loss', 'Fat Loss'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('recomp', 'Body Recomposition'), ('general_fitness', 'General Fitness')], default='build_muscle', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If True, template is visible to all trainers')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_program_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'program_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='program_tem_created_f8dd78_idx'), models.Index(fields=['is_public'], name='program_tem_is_publ_6a5977_idx'), models.Index(fields=['goal_type'], name='program_tem_goal_ty_fdf3d4_idx'), models.Index(fields=['difficulty_level'], name='program_tem_difficu_a3bc52_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('workout_schedule', models.JSONField(default=dict, help_text='Workout details for this specific week')),
                ('nutrition_adjustments', models.JSONField(default=dict, help_text='Adjustments to base nutrition (e.g., surplus/deficit changes)')),
                ('intensity_modifier', models.FloatField(default=1.0, help_text='Multiplier for weight/intensity (1.0 = 100%)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('volume_modifier', models.FloatField(default=1.0, help_text='Multiplier for sets/reps volume (1.0 = 100%)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('is_deload', models.BooleanField(default=False, help_text='Mark as deload/recovery week')),
                ('notes', models.TextField(blank=True, help_text='Special instructions or notes for this week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='workouts.program')),
            ],
            options={
                'db_table': 'program_weeks',
                'ordering': ['week_number'],
                'indexes': [models.Index(fields=['program', 'week_number'], name='program_wee_program_011eeb_idx')],
                'unique_together': {('program', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyNutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('protein_goal', models.PositiveIntegerField(default=0, help_text='Daily protein goal in grams')),
                ('carbs_goal', models.PositiveIntegerField(default=0, help_text='Daily carbohydrate goal in grams')),
                ('fat_goal', models.PositiveIntegerField(default=0, help_text='Daily fat goal in grams')),
                ('calories_goal', models.PositiveIntegerField(default=0, help_text='Daily calorie goal')),
                ('training_day_carbs_modifier', models.FloatField(default=1.0, help_text='Carb multiplier for training days', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('rest_day_carbs_modifier', models.FloatField(default=0.8, help_text='Carb multiplier for rest days', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('high_day_calories', models.PositiveIntegerField(blank=True, help_text='Optional: Calories for high days (refeed)', null=True)),
                ('low_day_calories', models.PositiveIntegerField(blank=True, help_text='Optional: Calories for low days (deficit)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Special dietary notes for this week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_nutrition_plans', to='workouts.program')),
            ],
            options={
                'db_table': 'weekly_nutrition_plans',
                'ordering': ['week_number'],
                'indexes': [models.Index(fields=['program', 'week_number'], name='weekly_nutr_program_e572f2_idx')],
                'unique_together': {('program', 'week_number')},
            },
        ),
    ]
