# Generated by Django 6.0.1 on 2026-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_programtemplate_programweek_weeklynutritionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='missed_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of dates when the trainee missed their workout'),
        ),
    ]
