# Generated by Django 6.0.1 on 2026-01-31 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_add_missed_dates_to_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Preset name (e.g., 'Training Day', 'Rest Day', 'Growth Day')", max_length=100)),
                ('calories', models.PositiveIntegerField(default=2000)),
                ('protein', models.PositiveIntegerField(default=150, help_text='Protein in grams')),
                ('carbs', models.PositiveIntegerField(default=200, help_text='Carbs in grams')),
                ('fat', models.PositiveIntegerField(default=70, help_text='Fat in grams')),
                ('frequency_per_week', models.PositiveIntegerField(blank=True, help_text='How many times per week this preset is typically used', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this preset is shown as the primary/default option')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_macro_presets', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='macro_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'macro_presets',
                'ordering': ['sort_order', '-is_default', 'name'],
                'indexes': [models.Index(fields=['trainee'], name='macro_prese_trainee_d92bde_idx'), models.Index(fields=['trainee', 'is_default'], name='macro_prese_trainee_60401b_idx')],
            },
        ),
    ]
