# Generated by Django 6.0.1 on 2026-01-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_add_macro_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL for this exercise', null=True),
        ),
    ]
