# Generated by Django 6.0.1 on 2026-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_add_exercise_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL for this program', null=True),
        ),
        migrations.AddField(
            model_name='programtemplate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL for this program template', null=True),
        ),
    ]
