# Generated by Django 6.0.1 on 2026-02-21 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_add_image_url_to_programs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, default='', help_text="KILO category or custom classification (e.g., 'Squat', 'Press', 'Cable Fly')", max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Exercise difficulty: beginner (machines/cables), intermediate (free weights), advanced (complex/specialty)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group', 'difficulty_level'], name='exercises_muscle__49226e_idx'),
        ),
    ]
