# Generated by Django 6.0.1 on 2026-02-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_add_exercise_difficulty_and_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='Thumbnail image URL for this exercise', max_length=2048, null=True),
        ),
    ]
