# Generated by Django 6.0.1 on 2026-02-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_expand_exercise_image_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='suitable_for_goals',
            field=models.JSONField(blank=True, default=list, help_text='Training goals this exercise is best suited for. Values from: build_muscle, fat_loss, strength, endurance, recomp, general_fitness'),
        ),
    ]
