# Generated by Django 6.0.1 on 2026-03-05 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_add_exercise_suitable_for_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('fields', models.JSONField(help_text='Form field definitions: [{id, type: text|number|scale|multi_choice|photo, label, required, options}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkin_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckInAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_assignments', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.checkintemplate')),
            ],
            options={
                'db_table': 'checkin_assignments',
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='check_circle', max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text="List of day names for custom frequency, e.g. ['Monday', 'Wednesday', 'Friday']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.habit')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_data', models.JSONField(help_text='Suggestion details: {current_weight, suggested_weight, current_reps, suggested_reps, current_sets, suggested_sets, rationale, confidence}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dismissed', 'Dismissed'), ('applied', 'Applied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_suggestions', to='workouts.exercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_suggestions', to='workouts.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_progressions', to=settings.AUTH_USER_MODEL)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='progression_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progression_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='progress_photos/%Y/%m/')),
                ('category', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back'), ('other', 'Other')], default='front', max_length=10)),
                ('date', models.DateField()),
                ('measurements', models.JSONField(blank=True, default=dict, help_text='Body measurements: {waist_cm, chest_cm, arms_cm, hips_cm, thighs_cm}')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_photos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('sports', 'Sports'), ('outdoor', 'Outdoor'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('default_calories_per_minute', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(50.0)])),
                ('is_public', models.BooleanField(default=False, help_text='True for system defaults, False for trainer-created templates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workout_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(help_text='Completed form responses: [{field_id, value}]')),
                ('trainer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workouts.checkinassignment')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkin_responses',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['trainee', '-submitted_at'], name='checkin_res_trainee_f1a33b_idx'), models.Index(fields=['assignment'], name='checkin_res_assignm_6aa358_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='checkintemplate',
            index=models.Index(fields=['trainer'], name='checkin_tem_trainer_7196de_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinassignment',
            index=models.Index(fields=['trainee', 'is_active'], name='checkin_ass_trainee_135645_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinassignment',
            index=models.Index(fields=['next_due_date'], name='checkin_ass_next_du_3d7ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['trainee', 'is_active'], name='habits_trainee_27d724_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['trainer'], name='habits_trainer_fe7d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['trainee', 'date'], name='habit_logs_trainee_2b5463_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='habit_logs_habit_i_bab3fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
        migrations.AddIndex(
            model_name='progressionsuggestion',
            index=models.Index(fields=['program', 'status'], name='progression_program_c49c90_idx'),
        ),
        migrations.AddIndex(
            model_name='progressionsuggestion',
            index=models.Index(fields=['trainee', 'status'], name='progression_trainee_34ac3d_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['trainee', 'date'], name='progress_ph_trainee_783a08_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['trainee', 'category'], name='progress_ph_trainee_a5a7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['category'], name='workout_tem_categor_c67260_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['is_public'], name='workout_tem_is_publ_644737_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['created_by'], name='workout_tem_created_a26fd7_idx'),
        ),
    ]
