# Generated by Django 6.0.1 on 2026-03-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_migrate_existing_goals'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nutritiondayplan',
            new_name='nutrition_d_trainee_242b58_idx',
            old_name='nut_day_plan_trainee_date_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritiontemplate',
            new_name='nutrition_t_templat_21a609_idx',
            old_name='nutrition_te_templat_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritiontemplate',
            new_name='nutrition_t_is_syst_809cab_idx',
            old_name='nutrition_te_is_syst_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritiontemplate',
            new_name='nutrition_t_created_7335c2_idx',
            old_name='nutrition_te_created_idx',
        ),
        migrations.RenameIndex(
            model_name='nutritiontemplateassignment',
            new_name='nutrition_t_trainee_a4125d_idx',
            old_name='nut_tmpl_assign_trainee_idx',
        ),
    ]
