# Generated by Django 6.0.1 on 2026-03-06 00:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_fix_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('serving_size', models.FloatField(default=1.0, help_text='Amount per serving (e.g. 100 for 100g)', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('serving_unit', models.CharField(choices=[('g', 'Grams'), ('oz', 'Ounces'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('piece', 'Pieces'), ('slice', 'Slices'), ('ml', 'Milliliters'), ('fl_oz', 'Fluid Ounces'), ('scoop', 'Scoops'), ('serving', 'Servings')], default='g', max_length=10)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0, help_text='Protein per serving in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(default=0, help_text='Carbohydrates per serving in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.FloatField(default=0, help_text='Fat per serving in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.FloatField(default=0, help_text='Fiber per serving in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.FloatField(default=0, help_text='Sugar per serving in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.FloatField(default=0, help_text='Sodium per serving in milligrams', validators=[django.core.validators.MinValueValidator(0)])),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='UPC/EAN barcode for scanning', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='True for system foods, False for trainer-created custom foods')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer who created this food item (null for system foods)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_number', models.PositiveSmallIntegerField(help_text='Meal number (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('meal_name', models.CharField(blank=True, default='', help_text='Optional label: Breakfast, Lunch, Snack, etc.', max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_logs',
                'ordering': ['date', 'meal_number'],
            },
        ),
        migrations.CreateModel(
            name='MealLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', help_text='Name for freeform entries (used when food_item is null)', max_length=255)),
                ('quantity', models.FloatField(default=1.0, help_text='Number of servings consumed', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('serving_unit', models.CharField(choices=[('g', 'Grams'), ('oz', 'Ounces'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('piece', 'Pieces'), ('slice', 'Slices'), ('ml', 'Milliliters'), ('fl_oz', 'Fluid Ounces'), ('scoop', 'Scoops'), ('serving', 'Servings')], default='serving', max_length=10)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_mode', models.CharField(choices=[('total_fat', 'Total Fat'), ('added_fat', 'Added Fat')], default='total_fat', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, help_text='Reference to food database item (null for freeform entries)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_log_entries', to='workouts.fooditem')),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.meallog')),
            ],
            options={
                'db_table': 'meal_log_entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name'], name='food_items_name_7242ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_public'], name='food_items_is_publ_54ac66_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['created_by'], name='food_items_created_e61bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['brand'], name='food_items_brand_303ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['trainee', 'date'], name='meal_logs_trainee_f5f990_idx'),
        ),
        migrations.AddConstraint(
            model_name='meallog',
            constraint=models.UniqueConstraint(fields=('trainee', 'date', 'meal_number'), name='unique_meal_per_day'),
        ),
        migrations.AddIndex(
            model_name='meallogentry',
            index=models.Index(fields=['meal_log'], name='meal_log_en_meal_lo_5f181c_idx'),
        ),
        migrations.AddIndex(
            model_name='meallogentry',
            index=models.Index(fields=['food_item'], name='meal_log_en_food_it_b10687_idx'),
        ),
    ]
