# Generated by Django 6.0.1 on 2026-03-10 03:20

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_update_shredded_massive_rulesets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('trainer', 'Trainer'), ('user', 'User')], help_text='Who/what triggered this decision.', max_length=10)),
                ('decision_type', models.CharField(help_text='Type of decision: exercise_swap, progression, deload_rewrite, load_prescription, plan_generation, undo, etc.', max_length=100)),
                ('context', models.JSONField(default=dict, help_text='Where the decision applies: {plan_id, week_id, session_id, slot_id} or {nutrition_day_id}.')),
                ('inputs_snapshot', models.JSONField(default=dict, help_text='Canonical snapshot of all inputs used to make the decision.')),
                ('constraints_applied', models.JSONField(default=dict, help_text='Filters and constraints that narrowed the options.')),
                ('options_considered', models.JSONField(default=dict, help_text='Top N options with score breakdown: [{option, score, reasons}, ...].')),
                ('final_choice', models.JSONField(default=dict, help_text='The option that was selected.')),
                ('reason_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Machine-readable reason codes (e.g., ['fatigue_high', 'pain_flag']).")),
                ('override_info', models.JSONField(blank=True, help_text='If a trainer/user overrode this decision: {overridden_by, original_choice, reason}.', null=True)),
            ],
            options={
                'db_table': 'decision_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UndoSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('slot', 'Slot'), ('session', 'Session'), ('week', 'Week'), ('exercise', 'Exercise'), ('nutrition_day', 'Nutrition Day')], help_text='Granularity of what was changed.', max_length=20)),
                ('before_state', models.JSONField(help_text='Full state snapshot before the decision was applied.')),
                ('after_state', models.JSONField(help_text='Full state snapshot after the decision was applied.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, help_text='Timestamp when this snapshot was used to revert. Null if not yet reverted.', null=True)),
            ],
            options={
                'db_table': 'undo_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Alternative names for this exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='athletic_attribute_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('power', 'Power'), ('elasticity', 'Elasticity'), ('rate_of_force_development', 'Rate of Force Development'), ('reactive_strength_index', 'Reactive Strength Index'), ('speed_linear', 'Speed Linear'), ('agility_multi_directional', 'Agility Multi-Directional'), ('coordination', 'Coordination'), ('stiffness', 'Stiffness'), ('deceleration_capacity', 'Deceleration Capacity'), ('work_capacity', 'Work Capacity')], max_length=50), blank=True, default=list, help_text='Athletic attribute tags (e.g., power, elasticity). Can be empty.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='athletic_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='Constraint flags: {impact_level, ground_contacts_level, space_required, surface_required, skill_demand}. Values: low/moderate/high or true/false or small/medium/large.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='athletic_skill_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('jump_vertical', 'Jump Vertical'), ('jump_horizontal', 'Jump Horizontal'), ('jump_lateral', 'Jump Lateral'), ('hop_single_leg_vertical', 'Hop Single-Leg Vertical'), ('hop_single_leg_horizontal', 'Hop Single-Leg Horizontal'), ('bound_alternating', 'Bound Alternating'), ('landing_and_deceleration', 'Landing and Deceleration'), ('sprint_acceleration', 'Sprint Acceleration'), ('sprint_max_velocity', 'Sprint Max Velocity'), ('change_of_direction_cut', 'Change of Direction Cut'), ('shuffle_and_lateral', 'Shuffle and Lateral Movement'), ('throw_overhead', 'Throw Overhead'), ('throw_rotational', 'Throw Rotational'), ('throw_chest_pass', 'Throw Chest Pass'), ('olympic_lift_derivative', 'Olympic Lift Derivative'), ('upper_body_plyometric', 'Upper-Body Plyometric'), ('medicine_ball_slam', 'Medicine Ball Slam'), ('medicine_ball_scoop_toss', 'Medicine Ball Scoop Toss'), ('reactive_agility_cue_based', 'Reactive Agility Cue-Based')], max_length=50), blank=True, default=list, help_text='Athletic skill tags (e.g., jump_vertical, sprint_acceleration). Can be empty.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_optional',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Equipment that enhances the exercise but isn't required."),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Equipment that MUST be available (e.g., ['barbell', 'squat_rack'])."),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_contribution_map',
            field=models.JSONField(blank=True, default=dict, help_text="Map of {detailed_muscle_group: weight}. Weights must sum to 1.0. E.g., {'quads': 0.6, 'glutes': 0.3, 'calves': 0.1}"),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pattern_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('knee_dominant', 'Knee Dominant'), ('hip_dominant', 'Hip Dominant'), ('horizontal_push', 'Horizontal Push'), ('horizontal_pull', 'Horizontal Pull'), ('vertical_push', 'Vertical Push'), ('vertical_pull', 'Vertical Pull'), ('trunk_anti_extension', 'Trunk Anti-Extension'), ('trunk_anti_flexion', 'Trunk Anti-Flexion'), ('trunk_anti_rotation', 'Trunk Anti-Rotation'), ('trunk_rotation', 'Trunk Rotation'), ('trunk_lateral_flexion', 'Trunk Lateral Flexion'), ('trunk_anti_lateral_flexion', 'Trunk Anti-Lateral Flexion'), ('pelvis_flexion_emphasis', 'Pelvis Flexion Emphasis'), ('pelvis_extension_emphasis', 'Pelvis Extension Emphasis'), ('locomotion', 'Locomotion'), ('carries', 'Carries')], max_length=50), blank=True, default=list, help_text='Movement intent tags (e.g., knee_dominant, horizontal_push). Drives program coverage.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='plane',
            field=models.CharField(blank=True, choices=[('sagittal', 'Sagittal (Forward/Back)'), ('frontal', 'Frontal (Side-to-Side)'), ('transverse', 'Transverse (Rotation)'), ('mixed', 'Mixed / Multi-Planar')], default='', help_text='Primary movement plane (sagittal, frontal, transverse, mixed).', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle_group',
            field=models.CharField(blank=True, choices=[('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('hip_adductors', 'Hip Adductors'), ('hip_abductors', 'Hip Abductors'), ('hip_flexors', 'Hip Flexors'), ('spinal_erectors', 'Spinal Erectors'), ('lats', 'Lats'), ('mid_back', 'Mid-Back'), ('upper_traps', 'Upper Traps'), ('rear_delts', 'Rear Delts'), ('side_delts', 'Side Delts'), ('front_delts', 'Front Delts'), ('chest', 'Chest'), ('triceps', 'Triceps'), ('biceps', 'Biceps'), ('forearms_and_grip', 'Forearms and Grip'), ('abs_rectus', 'Abs (Rectus)'), ('obliques', 'Obliques'), ('deep_core', 'Deep Core')], default='', help_text='Primary target muscle from the detailed v6.5 taxonomy.', max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rom_bias',
            field=models.CharField(blank=True, choices=[('lengthened', 'Lengthened Bias (Peak Tension in Stretched Position)'), ('mid_range', 'Mid-Range Bias (Peak Tension Near Middle)'), ('shortened', 'Shortened Bias (Peak Tension Near Shortened Position)'), ('mixed', 'Mixed (Unclear or Blended)')], default='', help_text='Where peak tension occurs in the range of motion.', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscle_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('quads', 'Quads'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('hip_adductors', 'Hip Adductors'), ('hip_abductors', 'Hip Abductors'), ('hip_flexors', 'Hip Flexors'), ('spinal_erectors', 'Spinal Erectors'), ('lats', 'Lats'), ('mid_back', 'Mid-Back'), ('upper_traps', 'Upper Traps'), ('rear_delts', 'Rear Delts'), ('side_delts', 'Side Delts'), ('front_delts', 'Front Delts'), ('chest', 'Chest'), ('triceps', 'Triceps'), ('biceps', 'Biceps'), ('forearms_and_grip', 'Forearms and Grip'), ('abs_rectus', 'Abs (Rectus)'), ('obliques', 'Obliques'), ('deep_core', 'Deep Core')], max_length=30), blank=True, default=list, help_text='Secondary muscles worked by this exercise.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='stance',
            field=models.CharField(blank=True, choices=[('supine', 'Supine'), ('prone', 'Prone'), ('quadruped', 'Quadruped'), ('tall_kneeling', 'Tall-Kneeling'), ('half_kneeling', 'Half-Kneeling'), ('seated_supported', 'Seated Supported'), ('standing_supported', 'Standing (Rack/Machine-Supported)'), ('bilateral_standing', 'Bilateral Standing (Symmetrical)'), ('staggered', 'Staggered (Split-Stance, Both Feet Down)'), ('split_squat_lunge', 'Split Squat / Lunge (True Unilateral Bias)'), ('single_leg', 'Single-Leg (True Single Support)'), ('athletic_multidirectional', 'Athletic / Multidirectional'), ('hang_support', 'Hang / Support')], default='', help_text='How the user stands/positions during the exercise.', max_length=40),
        ),
        migrations.AddField(
            model_name='exercise',
            name='standardization_block',
            field=models.JSONField(blank=True, default=dict, help_text='Execution standards: {what_counts[], feel_checks[], fail_flags[], default_dials[], assess_hooks[]}. Defines rep quality and safety.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='swap_seed_ids',
            field=models.JSONField(blank=True, default=dict, help_text='Pre-computed swap candidates: {recommended_same_muscle_ids[], recommended_same_pattern_ids[]}.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number, incremented on each edit.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], default='other', help_text='Legacy single muscle group. Use muscle_contribution_map for v6.5+ logic.', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='suitable_for_goals',
            field=models.JSONField(blank=True, default=list, help_text='Training goals this exercise is best suited for.'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['stance'], name='exercises_stance_acdacc_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['plane'], name='exercises_plane_74ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['primary_muscle_group'], name='exercises_primary_c74680_idx'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='The user who triggered (null for system-triggered decisions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='undo_snapshot',
            field=models.OneToOneField(blank=True, help_text='Snapshot for reverting this decision. Null if not undoable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision', to='workouts.undosnapshot'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['decision_type'], name='decision_lo_decisio_e9acc2_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['actor_type'], name='decision_lo_actor_t_41aeed_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['timestamp'], name='decision_lo_timesta_497a74_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['actor'], name='decision_lo_actor_i_628b12_idx'),
        ),
    ]
