# Generated by Django 6.0.1 on 2026-03-10 03:30

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_v65_exercise_tags_decision_log_undo_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionlog',
            name='actor_type',
            field=models.CharField(choices=[('system', 'System'), ('trainer', 'Trainer'), ('user', 'User')], help_text='Who/what triggered this decision.', max_length=20),
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='options_considered',
            field=models.JSONField(default=list, help_text='Top N options with score breakdown: [{option, score, reasons}, ...].'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pattern_tags'], name='exercises_pattern_tags_gin'),
        ),
    ]
