# Generated by Django 6.0.1 on 2026-03-10 03:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_v65_review_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftMax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e1rm_current', models.DecimalField(decimal_places=2, default=0, help_text='Current estimated 1RM from best qualifying set.', max_digits=8)),
                ('e1rm_history', models.JSONField(blank=True, default=list, help_text='List of {date, value, source_set_id, formula}.')),
                ('tm_current', models.DecimalField(decimal_places=2, default=0, help_text='Training max = e1RM × tm_percentage. Coach-editable.', max_digits=8)),
                ('tm_percentage', models.DecimalField(decimal_places=2, default=90, help_text='TM as percentage of e1RM (default 90%). Range: 80-100.', max_digits=5, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100)])),
                ('tm_history', models.JSONField(blank=True, default=list, help_text='List of {date, value, reason, trigger}.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lift_maxes', to='workouts.exercise')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='lift_maxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lift_maxes',
                'indexes': [models.Index(fields=['trainee'], name='lift_maxes_trainee_638d73_idx'), models.Index(fields=['exercise'], name='lift_maxes_exercis_811902_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainee', 'exercise'), name='unique_max_per_exercise_per_trainee')],
            },
        ),
        migrations.CreateModel(
            name='LiftSetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(help_text='The date this set was performed.')),
                ('set_number', models.PositiveIntegerField(help_text='Ordinal within the exercise for this session (1-based).')),
                ('entered_load_value', models.DecimalField(decimal_places=2, default=0, help_text='The load value as the user typed it.', max_digits=8)),
                ('entered_load_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', max_length=5)),
                ('load_entry_mode', models.CharField(choices=[('total_load', 'Total Load'), ('per_hand', 'Per Hand'), ('bodyweight_plus_external', 'Bodyweight + External')], default='total_load', help_text='How the user entered the load (total, per-hand, bodyweight+external).', max_length=30)),
                ('canonical_external_load_value', models.DecimalField(decimal_places=2, default=0, help_text='Normalized external load for workload math. Per-hand entries are doubled. BW+external is just the external portion.', max_digits=8)),
                ('canonical_external_load_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', max_length=5)),
                ('workload_eligible', models.BooleanField(default=True, help_text='False if no valid load×reps representation exists (e.g., timed-only set).')),
                ('completed_reps', models.PositiveIntegerField(default=0, help_text='Reps actually completed.')),
                ('completed_time_seconds', models.PositiveIntegerField(blank=True, help_text='Duration for timed sets (planks, carries, etc.).', null=True)),
                ('completed_distance_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Distance for carries, sprints, etc.', max_digits=8, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, help_text='Rate of Perceived Exertion (1-10, half-points allowed).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('standardization_pass', models.BooleanField(default=True, help_text="Did this set meet the exercise's standardization criteria? Only passing sets update e1RM.")),
                ('set_workload_value', models.DecimalField(decimal_places=2, default=0, help_text='canonical_external_load × completed_reps (or 0 if not workload_eligible).', max_digits=12)),
                ('set_workload_unit', models.CharField(default='lb_reps', help_text='Unit of workload: lb_reps or kg_reps.', max_length=10)),
                ('tempo_modifier', models.CharField(blank=True, default='', help_text="Tempo prescription if any (e.g., '3-1-2-0' = eccentric-pause-concentric-pause).", max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lift_set_logs', to='workouts.exercise')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='lift_set_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lift_set_logs',
                'ordering': ['session_date', 'set_number'],
                'indexes': [models.Index(fields=['trainee', 'session_date'], name='lift_set_lo_trainee_c49ec5_idx'), models.Index(fields=['trainee', 'exercise'], name='lift_set_lo_trainee_906d4b_idx'), models.Index(fields=['exercise', 'session_date'], name='lift_set_lo_exercis_09fb19_idx'), models.Index(fields=['session_date'], name='lift_set_lo_session_a3f022_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainee', 'exercise', 'session_date', 'set_number'), name='unique_set_per_exercise_per_session')],
            },
        ),
    ]
