# Generated by Django 6.0.1 on 2026-03-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0020_liftmax_liftsetlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liftsetlog',
            name='standardization_pass',
            field=models.BooleanField(default=False, help_text="Did this set meet the exercise's standardization criteria? Only passing sets update e1RM. Default False (fail-closed)."),
        ),
    ]
