# Generated by Django 6.0.1 on 2026-03-10 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_alter_liftsetlog_standardization_pass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadFactTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('exercise', 'Exercise'), ('session', 'Session')], help_text='When this fact is shown: after an exercise or at end of session.', max_length=10)),
                ('template_text', models.TextField(help_text='Template with placeholders: {exercise_name}, {total_workload}, {total_reps}, {set_count}, {unit}, {delta_percent}, {week_total}, {top_exercise}, {muscle_group}.')),
                ('condition_rules', models.JSONField(blank=True, default=dict, help_text="Rules for when to select this template. E.g., {'min_workload': 1000, 'has_comparison': true, 'delta_positive': true}.")),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority. First matching template wins.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer who created this template (null = system default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workload_fact_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workload_fact_templates',
                'ordering': ['priority', 'scope'],
                'indexes': [models.Index(fields=['scope', 'is_active', 'priority'], name='workload_fa_scope_206fb5_idx')],
            },
        ),
    ]
