# Generated by Django 6.0.1 on 2026-03-10 04:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0022_workloadfacttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveIntegerField()),
                ('is_deload', models.BooleanField(default=False)),
                ('intensity_modifier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for load/intensity (0.30–2.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.30')), django.core.validators.MaxValueValidator(Decimal('2.00'))])),
                ('volume_modifier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier for total volume (0.30–2.00).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.30')), django.core.validators.MaxValueValidator(Decimal('2.00'))])),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'plan_weeks',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='PlanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday … 6=Sunday.')),
                ('label', models.CharField(help_text="Human-readable label, e.g., 'Upper A', 'Push Day'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the week.')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.planweek')),
            ],
            options={
                'db_table': 'plan_sessions',
                'ordering': ['order', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='SplitTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days_per_week', models.PositiveIntegerField(help_text='Number of training days per week.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('session_definitions', models.JSONField(help_text='Ordered list of session blueprints. Each entry: {label: str, muscle_groups: [str], pattern_focus: [str]}. Length must equal days_per_week.')),
                ('goal_type', models.CharField(blank=True, choices=[('build_muscle', 'Build Muscle'), ('fat_loss', 'Fat Loss'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('recomp', 'Recomposition'), ('general_fitness', 'General Fitness')], default='', help_text='Primary goal this split is designed for (blank = general).', max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='True for platform-wide defaults (PPL, Upper/Lower, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer who created this template (null = system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'split_templates',
                'ordering': ['days_per_week', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('goal', models.CharField(choices=[('build_muscle', 'Build Muscle'), ('fat_loss', 'Fat Loss'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('recomp', 'Recomposition'), ('general_fitness', 'General Fitness')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('duration_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Trainer or admin who created this plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_plans', to=settings.AUTH_USER_MODEL)),
                ('split_template', models.ForeignKey(blank=True, help_text='The split template used to generate this plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='workouts.splittemplate')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='planweek',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='workouts.trainingplan'),
        ),
        migrations.CreateModel(
            name='PlanSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Display order within the session (1-based).')),
                ('slot_role', models.CharField(choices=[('primary_compound', 'Primary Compound'), ('secondary_compound', 'Secondary Compound'), ('accessory', 'Accessory'), ('isolation', 'Isolation')], help_text='Role of this slot in the session structure.', max_length=25)),
                ('sets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('reps_min', models.PositiveIntegerField(help_text='Minimum reps in the prescribed rep range.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('reps_max', models.PositiveIntegerField(help_text='Maximum reps in the prescribed rep range.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('rest_seconds', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('load_prescription_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of Training Max to prescribe (e.g., 80.00).', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('swap_options_cache', models.JSONField(blank=True, default=dict, help_text='Pre-computed swap candidates: {same_muscle: [id, ...], same_pattern: [id, ...], explore: [id, ...]}.')),
                ('exercise', models.ForeignKey(help_text='The assigned exercise for this slot.', on_delete=django.db.models.deletion.PROTECT, related_name='plan_slots', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workouts.plansession')),
            ],
            options={
                'db_table': 'plan_slots',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['session', 'order'], name='plan_slots_session_25dff0_idx'), models.Index(fields=['exercise'], name='plan_slots_exercis_d29ffe_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='unique_slot_order_per_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='plansession',
            constraint=models.UniqueConstraint(fields=('week', 'day_of_week'), name='unique_session_per_day_per_week'),
        ),
        migrations.AddIndex(
            model_name='splittemplate',
            index=models.Index(fields=['days_per_week', 'goal_type'], name='split_templ_days_pe_78e7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='splittemplate',
            index=models.Index(fields=['is_system'], name='split_templ_is_syst_41be10_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['trainee', 'status'], name='training_pl_trainee_a8b73a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['created_by'], name='training_pl_created_db4fe7_idx'),
        ),
        migrations.AddConstraint(
            model_name='planweek',
            constraint=models.UniqueConstraint(fields=('plan', 'week_number'), name='unique_week_per_plan'),
        ),
    ]
