# Generated by Django 6.0.1 on 2026-03-10 05:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_training_plan_split_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planslot',
            name='modality_details',
            field=models.JSONField(blank=True, default=dict, help_text='Modality-specific parameters (e.g., paired_exercise_id for supersets, tempo for eccentrics, fatigue_override for myo-reps).'),
        ),
        migrations.AddField(
            model_name='planslot',
            name='modality_volume_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed volume contribution: sets × modality volume_multiplier.', max_digits=6),
        ),
        migrations.CreateModel(
            name='SetStructureModality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('volume_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to each working set for volume counting (e.g., 0.67 for drop sets).', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('3.00'))])),
                ('use_when', models.JSONField(blank=True, default=list, help_text='List of conditions describing when to use this modality.')),
                ('avoid_when', models.JSONField(blank=True, default=list, help_text='List of conditions describing when to avoid this modality.')),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modalities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'set_structure_modalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='planslot',
            name='set_structure_modality',
            field=models.ForeignKey(blank=True, help_text='The set structure modality for this slot (e.g., straight sets, drop sets).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_slots', to='workouts.setstructuremodality'),
        ),
        migrations.CreateModel(
            name='ModalityGuardrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('avoid', 'Avoid'), ('require', 'Require')], max_length=10)),
                ('condition_field', models.CharField(help_text="Field to check: 'exercise.athletic_skill_tags', 'slot.reps_max', 'slot.slot_role', etc.", max_length=100)),
                ('condition_operator', models.CharField(choices=[('has_any', 'Has Any'), ('has_none', 'Has None'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equals'), ('in', 'In List')], max_length=20)),
                ('condition_value', models.JSONField(help_text='Value to compare against. JSON-encoded.')),
                ('error_message', models.CharField(help_text='Human-readable message when guardrail is violated.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrails', to='workouts.setstructuremodality')),
            ],
            options={
                'db_table': 'modality_guardrails',
                'ordering': ['modality', 'rule_type'],
                'indexes': [models.Index(fields=['modality', 'is_active'], name='modality_gu_modalit_86f428_idx')],
            },
        ),
    ]
