# Generated by Django 6.0.1 on 2026-03-10 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_modality_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('progression_type', models.CharField(choices=[('staircase_percent', 'Staircase Percent'), ('rep_staircase', 'Rep Staircase'), ('wave_by_month', 'Wave-by-Month'), ('double_progression', 'Double Progression'), ('linear', 'Linear')], max_length=30)),
                ('rules', models.JSONField(default=dict, help_text='Progression rules. Structure varies by type. E.g., {step_pct: 2.5, work_weeks: 4} for staircase_percent, {rep_step: 1, load_increment_upper_lb: 5} for rep_staircase.')),
                ('deload_rules', models.JSONField(default=dict, help_text='Deload configuration. E.g., {volume_drop_pct: 40, intensity_drop_pct: 10, trigger_after_weeks: 4}.')),
                ('failure_rules', models.JSONField(default=dict, help_text="Failure handling. E.g., {consecutive_failures_for_deload: 2, load_reduction_pct: 5, action: 'repeat_week'}.")),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_progression_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progression_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='planslot',
            name='progression_profile',
            field=models.ForeignKey(blank=True, help_text='Slot-level progression profile override. Falls back to plan default if null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_slots', to='workouts.progressionprofile'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='default_progression_profile',
            field=models.ForeignKey(blank=True, help_text='Default progression profile for all slots in this plan. Overrideable per slot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_plans', to='workouts.progressionprofile'),
        ),
        migrations.CreateModel(
            name='ProgressionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('progression', 'Progression'), ('deload', 'Deload'), ('failure', 'Failure'), ('reset', 'Reset'), ('hold', 'Hold')], max_length=20)),
                ('old_prescription', models.JSONField(default=dict, help_text='Previous prescription: {sets, reps_min, reps_max, load, percentage}.')),
                ('new_prescription', models.JSONField(default=dict, help_text='New prescription: {sets, reps_min, reps_max, load, percentage}.')),
                ('reason_codes', models.JSONField(default=list, help_text="Reason codes for the decision (e.g., ['all_sets_completed', 'rir_on_target']).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progression_events', to='workouts.decisionlog')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_events', to='workouts.exercise')),
                ('plan_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_events', to='workouts.planslot')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='progression_events', to=settings.AUTH_USER_MODEL)),
                ('progression_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='workouts.progressionprofile')),
            ],
            options={
                'db_table': 'progression_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', 'exercise'], name='progression_trainee_d599d2_idx'), models.Index(fields=['plan_slot', '-created_at'], name='progression_plan_sl_b164f2_idx')],
            },
        ),
    ]
