# Generated by Django 6.0.1 on 2026-03-10 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0025_progression_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='progressionprofile',
            index=models.Index(fields=['is_system', 'created_by'], name='progression_is_syst_10c54b_idx'),
        ),
    ]
