# Generated by Django 6.0.1 on 2026-03-10 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0026_progression_profile_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the trainee started the session.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the session was completed or abandoned.', null=True)),
                ('abandon_reason', models.CharField(blank=True, default='', help_text="Reason for abandonment (e.g., 'auto_abandoned_stale', user-provided).", max_length=255)),
                ('current_slot_index', models.PositiveIntegerField(default=0, help_text='Zero-based index of the current slot in the session.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_session', models.ForeignKey(blank=True, help_text='The PlanSession template this session was started from. SET_NULL so sessions survive plan deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='workouts.plansession')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'active_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField(help_text='1-based set number within this slot.')),
                ('prescribed_reps_min', models.PositiveIntegerField(help_text='Minimum reps prescribed.')),
                ('prescribed_reps_max', models.PositiveIntegerField(help_text='Maximum reps prescribed.')),
                ('prescribed_load', models.DecimalField(blank=True, decimal_places=2, help_text='Prescribed load value (null if no prescription / bodyweight).', max_digits=8, null=True)),
                ('prescribed_load_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', max_length=5)),
                ('completed_reps', models.PositiveIntegerField(blank=True, help_text='Reps actually completed (can be 0 for failed attempt).', null=True)),
                ('completed_load_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual load used.', max_digits=8, null=True)),
                ('completed_load_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', max_length=5)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, help_text='Rate of Perceived Exertion (1-10).', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('rest_prescribed_seconds', models.PositiveIntegerField(default=90, help_text='Prescribed rest duration in seconds.')),
                ('rest_actual_seconds', models.PositiveIntegerField(blank=True, help_text='Actual rest taken by trainee (tracked by client timer).', null=True)),
                ('set_started_at', models.DateTimeField(blank=True, help_text='When the trainee started this set.', null=True)),
                ('set_completed_at', models.DateTimeField(blank=True, help_text='When the trainee finished this set.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.activesession')),
                ('exercise', models.ForeignKey(help_text='Denormalized from PlanSlot for faster reads.', on_delete=django.db.models.deletion.CASCADE, related_name='active_set_logs', to='workouts.exercise')),
                ('plan_slot', models.ForeignKey(blank=True, help_text='The PlanSlot this set belongs to. SET_NULL to survive plan changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_set_logs', to='workouts.planslot')),
            ],
            options={
                'db_table': 'active_set_logs',
                'ordering': ['plan_slot__order', 'set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['trainee', 'status'], name='active_sess_trainee_093e98_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['trainee', '-created_at'], name='active_sess_trainee_47a1f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='activesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('trainee',), name='unique_active_session_per_trainee'),
        ),
        migrations.AddIndex(
            model_name='activesetlog',
            index=models.Index(fields=['active_session', 'status'], name='active_set__active__6fec3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='activesetlog',
            constraint=models.UniqueConstraint(fields=('active_session', 'plan_slot', 'set_number'), name='unique_set_per_slot_per_session'),
        ),
    ]
