# Generated by Django 6.0.1 on 2026-03-10 07:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0027_add_active_session_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_region', models.CharField(choices=[('neck', 'Neck'), ('shoulder_left', 'Left Shoulder'), ('shoulder_right', 'Right Shoulder'), ('upper_back', 'Upper Back'), ('lower_back', 'Lower Back'), ('chest', 'Chest'), ('elbow_left', 'Left Elbow'), ('elbow_right', 'Right Elbow'), ('wrist_left', 'Left Wrist'), ('wrist_right', 'Right Wrist'), ('hip_left', 'Left Hip'), ('hip_right', 'Right Hip'), ('knee_left', 'Left Knee'), ('knee_right', 'Right Knee'), ('ankle_left', 'Left Ankle'), ('ankle_right', 'Right Ankle'), ('other', 'Other')], max_length=30)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('midline', 'Midline')], default='midline', max_length=20)),
                ('pain_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sensation_type', models.CharField(choices=[('sharp', 'Sharp'), ('dull', 'Dull'), ('burning', 'Burning'), ('aching', 'Aching'), ('tightness', 'Tightness'), ('numbness', 'Numbness'), ('other', 'Other')], default='other', max_length=20)),
                ('onset_phase', models.CharField(blank=True, choices=[('warmup', 'Warm-up'), ('working_set', 'Working Set'), ('between_sets', 'Between Sets'), ('cooldown', 'Cooldown'), ('post_session', 'Post-Session')], default='', max_length=20)),
                ('warmup_effect', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'Same'), ('worse', 'Worse')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_events', to='workouts.activesession')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pain_events', to='workouts.exercise')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='pain_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pain_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', '-created_at'], name='pain_events_trainee_7a968d_idx'), models.Index(fields=['trainee', 'body_region'], name='pain_events_trainee_08a587_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_state', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('abandoned', 'Abandoned')], max_length=20)),
                ('rating_overall', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_muscle_feel', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_energy', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_enjoyment', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_difficulty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('friction_reasons', models.JSONField(default=list, help_text='List of friction reasons: too_heavy, too_light, time_pressure, pain, form_breakdown, fatigue, equipment_unavailable, other.')),
                ('recovery_concern', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='workouts.activesession')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', '-created_at'], name='session_fee_trainee_ee9c0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainerRoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('low_rating', 'Low Rating'), ('pain_report', 'Pain Report'), ('missed_sessions', 'Missed Sessions'), ('high_difficulty', 'High Difficulty'), ('recovery_concern', 'Recovery Concern'), ('form_breakdown', 'Form Breakdown')], max_length=30)),
                ('threshold_value', models.JSONField(default=dict, help_text='Threshold config. E.g., {min_rating: 2} for low_rating, {min_pain_score: 7} for pain_report, {consecutive_missed: 3} for missed_sessions.')),
                ('notification_method', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_routing_rules',
                'ordering': ['rule_type'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'rule_type'), name='unique_rule_per_trainer_per_type')],
            },
        ),
    ]
