# Generated by Django 6.0.1 on 2026-03-10 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0028_session_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramImportDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_review', max_length=20)),
                ('plan_name', models.CharField(blank=True, default='', help_text='Name for the resulting TrainingPlan.', max_length=200)),
                ('goal', models.CharField(blank=True, default='strength', max_length=50)),
                ('raw_csv', models.TextField(help_text='Original CSV content uploaded by the trainer.')),
                ('parsed_data', models.JSONField(default=dict, help_text='Parsed plan structure: weeks → sessions → slots.')),
                ('validation_errors', models.JSONField(default=list, help_text='List of validation errors found during parsing.')),
                ('validation_warnings', models.JSONField(default=list, help_text='Non-blocking warnings.')),
                ('total_weeks', models.PositiveSmallIntegerField(default=0)),
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('total_slots', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('trainee', models.ForeignKey(blank=True, help_text='Target trainee for this import.', limit_choices_to={'role': 'TRAINEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_drafts_received', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role__in': ['TRAINER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='import_drafts', to=settings.AUTH_USER_MODEL)),
                ('training_plan', models.ForeignKey(blank=True, help_text='The created TrainingPlan (set after confirmation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_draft', to='workouts.trainingplan')),
            ],
            options={
                'db_table': 'program_import_drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainer', '-created_at'], name='program_imp_trainer_eee32d_idx'), models.Index(fields=['status'], name='program_imp_status_185f84_idx')],
            },
        ),
    ]
