# Generated by Django 6.0.1 on 2026-03-10 08:20

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_program_import_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTagDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('pattern_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('athletic_skill_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('athletic_attribute_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('primary_muscle_group', models.CharField(blank=True, default='', max_length=30)),
                ('secondary_muscle_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list)),
                ('muscle_contribution_map', models.JSONField(blank=True, default=dict)),
                ('stance', models.CharField(blank=True, default='', max_length=40)),
                ('plane', models.CharField(blank=True, default='', max_length=20)),
                ('rom_bias', models.CharField(blank=True, default='', max_length=20)),
                ('equipment_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('equipment_optional', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('confidence_scores', models.JSONField(blank=True, default=dict, help_text='Per-field confidence: {field_name: 0.0-1.0}')),
                ('ai_reasoning', models.JSONField(blank=True, default=dict, help_text="Per-field reasoning from AI: {field_name: 'explanation'}")),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('exercise_version_at_creation', models.PositiveIntegerField(default=1, help_text='Exercise.version when this draft was created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_drafts', to='workouts.exercise')),
                ('requested_by', models.ForeignKey(limit_choices_to={'role__in': ['TRAINER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='tag_draft_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_tag_drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exercise', '-created_at'], name='exercise_ta_exercis_9a184f_idx'), models.Index(fields=['status'], name='exercise_ta_status_ad0bb6_idx'), models.Index(fields=['requested_by'], name='exercise_ta_request_3eed44_idx')],
            },
        ),
    ]
