# Generated by Django 6.0.1 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0030_exercise_tag_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undosnapshot',
            name='scope',
            field=models.CharField(choices=[('slot', 'Slot'), ('session', 'Session'), ('week', 'Week'), ('plan', 'Plan'), ('exercise', 'Exercise'), ('nutrition_day', 'Nutrition Day')], help_text='Granularity of what was changed.', max_length=20),
        ),
    ]
