# Generated by Django 6.0.1 on 2026-03-10 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_alter_undosnapshot_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(help_text='Video file (MP4, MOV, WebM). Max 50MB.', upload_to='video_analysis/%Y/%m/')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_analysis/thumbs/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('exercise_detected', models.CharField(blank=True, default='', help_text='Exercise name detected by AI.', max_length=200)),
                ('rep_count', models.PositiveSmallIntegerField(blank=True, help_text='Number of reps detected.', null=True)),
                ('form_score', models.FloatField(blank=True, help_text='Form quality score (0-10).', null=True)),
                ('observations', models.JSONField(blank=True, default=list, help_text='List of form observations from AI.')),
                ('confidence', models.FloatField(blank=True, help_text='Overall analysis confidence (0-1).', null=True)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict, help_text='Full AI response for debugging.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(blank=True, help_text='Matched exercise from library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_analyses', to='workouts.exercise')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', '-created_at'], name='video_analy_trainee_59a46c_idx'), models.Index(fields=['status'], name='video_analy_status_72327d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceMemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(help_text='Audio file (MP3, WAV, M4A, WebM). Max 25MB.', upload_to='voice_memos/%Y/%m/')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Audio duration in seconds.', null=True)),
                ('audio_format', models.CharField(blank=True, default='', help_text='Audio format (mp3, wav, m4a, webm).', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('transcript', models.TextField(blank=True, default='', help_text='Transcribed text from audio.')),
                ('transcription_confidence', models.FloatField(blank=True, help_text='Whisper transcription confidence (0-1).', null=True)),
                ('transcription_language', models.CharField(blank=True, default='', help_text="Detected language code (e.g., 'en').", max_length=10)),
                ('parsed_result', models.JSONField(blank=True, default=dict, help_text='Structured result from natural language parser.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if transcription or parsing failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(blank=True, help_text='DailyLog created from this voice memo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_memos', to='workouts.dailylog')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='voice_memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_memos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trainee', '-created_at'], name='voice_memos_trainee_c2f740_idx'), models.Index(fields=['status'], name='voice_memos_status_a68509_idx')],
            },
        ),
    ]
