# Generated by Django 6.0.1 on 2026-03-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0032_voice_memo_video_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, default='', max_length=100)),
                ('body_region', models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('core', 'Core')], max_length=20)),
                ('description', models.TextField()),
                ('origin', models.TextField(blank=True, default='')),
                ('insertion', models.TextField(blank=True, default='')),
                ('primary_movements', models.JSONField(default=list)),
                ('function_description', models.TextField(blank=True, default='')),
                ('training_tips', models.TextField(blank=True, default='')),
                ('common_exercises', models.JSONField(default=list)),
                ('sub_muscles', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'muscle_references',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
