# Generated by Django 6.0.1 on 2026-03-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0033_musclereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftsetlog',
            name='set_structure_modality',
            field=models.ForeignKey(blank=True, help_text='The set structure modality used for this set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lift_set_logs', to='workouts.setstructuremodality'),
        ),
        migrations.AddField(
            model_name='liftsetlog',
            name='set_type',
            field=models.CharField(choices=[('working', 'Working'), ('drop', 'Drop'), ('activation', 'Activation'), ('mini', 'Mini'), ('cluster', 'Cluster'), ('back_off', 'Back-Off'), ('top', 'Top')], default='working', help_text='Type of set within the modality context', max_length=20),
        ),
    ]
