# Generated by Django 6.0.1 on 2026-03-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0036_builder_intelligence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansession',
            name='day_role',
            field=models.CharField(blank=True, default='', help_text='Day role: upper_strength, lower_strength, hypertrophy, push, pull, legs, power, conditioning, rehab, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='plansession',
            name='day_stress',
            field=models.CharField(choices=[('high_neural', 'High Neural'), ('medium_mixed', 'Medium Mixed'), ('low_neural', 'Low Neural / Low Ortho'), ('local_fatigue', 'Local Fatigue Dominant'), ('aerobic', 'Aerobic Dominant'), ('restore', 'Restore'), ('optional', 'Optional')], default='medium_mixed', help_text='Neural/orthopedic stress level of this day.', max_length=20),
        ),
        migrations.AlterField(
            model_name='plansession',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated session duration including warm-up, work, rest, transitions.', null=True),
        ),
        migrations.AlterField(
            model_name='planslot',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Optional slots (finishers) are the first to be cut when session runs long.'),
        ),
        migrations.AlterField(
            model_name='planslot',
            name='pairing_group',
            field=models.PositiveIntegerField(blank=True, help_text='Shared integer for paired slots (supersets, tri-sets). Null = standalone.', null=True),
        ),
        migrations.AlterField(
            model_name='planslot',
            name='pairing_type',
            field=models.CharField(choices=[('straight', 'Straight Sequencing'), ('superset_antagonist', 'Superset (Antagonist)'), ('superset_non_competing', 'Superset (Non-Competing)'), ('superset_agonist', 'Superset (Agonist)'), ('tri_set', 'Tri-Set'), ('giant_set', 'Giant Set'), ('contrast', 'Contrast Pair'), ('complex', 'Complex'), ('potentiation', 'Potentiation Pair')], default='straight', help_text='How this slot is paired with others in its pairing_group.', max_length=25),
        ),
        migrations.AlterField(
            model_name='planslot',
            name='slot_role',
            field=models.CharField(choices=[('primary_compound', 'Primary Compound'), ('secondary_compound', 'Secondary Compound'), ('accessory', 'Accessory'), ('isolation', 'Isolation'), ('prep', 'Prep / Warm-Up / Activation'), ('technique', 'Technique / Power / Sprint'), ('main_strength', 'Main Strength'), ('hypertrophy_compound', 'Hypertrophy Compound'), ('hypertrophy_isolation', 'Hypertrophy Isolation'), ('unilateral_support', 'Unilateral Support'), ('trunk', 'Trunk / Core'), ('carry', 'Carry'), ('conditioning', 'Conditioning'), ('cooldown', 'Cooldown')], help_text='Role of this slot in the session structure.', max_length=25),
        ),
        migrations.AlterField(
            model_name='planslot',
            name='tempo_preset',
            field=models.CharField(blank=True, choices=[('power_speed', 'Power / Speed'), ('general_strength', 'General Strength'), ('pause_strength', 'Pause Strength'), ('joint_friendly', 'Joint-Friendly Control'), ('lengthened_hypertrophy', 'Lengthened-Bias Hypertrophy'), ('technique_preset', 'Technique / Strategy'), ('rehab_tolerance', 'Rehab Tolerance')], help_text='Tempo preset for this slot. Null = use default for the slot role.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='planweek',
            name='phase',
            field=models.CharField(choices=[('on_ramp', 'On-Ramp / Re-Entry'), ('accumulation', 'Accumulation / Build'), ('intensification', 'Intensification'), ('realization', 'Realization / Peak'), ('deload', 'Deload / Reset'), ('bridge', 'Bridge / Maintenance')], default='accumulation', help_text='Training phase for this week (on_ramp, accumulation, intensification, realization, deload, bridge).', max_length=20),
        ),
    ]
