# Generated by Django 6.0.1 on 2026-03-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0037_alter_plansession_day_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionfeedback',
            name='requested_action',
            field=models.CharField(blank=True, choices=[('no_followup', 'No Follow-up Needed'), ('adjust_next_time', 'Adjust Next Time'), ('message_trainer', 'Message Trainer'), ('review_with_video', 'Review With Video')], default='', help_text='What the trainee wants to happen next.', max_length=30),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session_volume_perception',
            field=models.CharField(blank=True, choices=[('too_much', 'Too Much'), ('about_right', 'About Right'), ('too_little', 'Too Little')], default='', help_text='Did the session feel too much, about right, or too little?', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='win_reasons',
            field=models.JSONField(default=list, help_text='List of win reasons: strong_performance, great_pump, smoother_technique, pain_free, confidence_boost, efficient_session.'),
        ),
        migrations.AlterField(
            model_name='trainerroutingrule',
            name='rule_type',
            field=models.CharField(choices=[('low_rating', 'Low Rating'), ('pain_report', 'Pain Report'), ('missed_sessions', 'Missed Sessions'), ('high_difficulty', 'High Difficulty'), ('recovery_concern', 'Recovery Concern'), ('form_breakdown', 'Form Breakdown'), ('pattern_fit_issue', 'Repeated Exercise Fit Issue'), ('pattern_confidence_drop', 'Falling Confidence Pattern')], max_length=30),
        ),
    ]
