# Generated by Django 6.0.1 on 2026-03-22 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0038_add_feedback_wins_and_pattern_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainTriageResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_1_answers', models.JSONField(default=dict, help_text='Structured: {body_region, side, pain_score, sensation_type, onset_phase, warmup_effect}')),
                ('round_2_answers', models.JSONField(default=dict, help_text='Structured: {load_sensitivity: better/same/worse, rom_sensitivity: better/same/worse, tempo_sensitivity: better/same/worse, support_helps: bool, previous_trigger: str}')),
                ('ai_suggestion', models.JSONField(default=dict, help_text='Full AI-generated suggestion payload for trainer-facing summary.')),
                ('ai_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=10)),
                ('proceed_decision', models.CharField(blank=True, choices=[('continue_as_planned', 'Continue As Planned'), ('continue_with_adjustment', 'Continue With Adjustment'), ('swap_exercise', 'Swap Exercise'), ('skip_slot', 'Skip This Exercise'), ('stop_session', 'End Session'), ('seek_clinical_review', 'Seek Clinical Review')], default='', max_length=30)),
                ('trainer_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_responses', to='workouts.activesession')),
                ('active_set_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_responses', to='workouts.activesetlog')),
                ('pain_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_response', to='workouts.painevent')),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='triage_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pain_triage_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PainInterventionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(help_text='Position in the remedy ladder (1-based).')),
                ('intervention_type', models.CharField(choices=[('cue_change', 'Cue Change'), ('tempo_pause', 'Tempo / Pause Change'), ('load_reduction', 'Load Reduction'), ('rom_reduction', 'ROM Reduction'), ('stance_change', 'Stance Change'), ('add_support', 'Add Support'), ('regression', 'Regression to Simpler Variation'), ('swap', 'Swap Exercise'), ('stop', 'Stop the Slot')], max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of what to try.')),
                ('applied', models.BooleanField(default=False, help_text='Did the trainee attempt this intervention?')),
                ('result', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('improved', 'Improved'), ('no_change', 'No Change'), ('worse', 'Worse'), ('skipped', 'Skipped')], default='', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Specifics like {new_load: 135, reduction_pct: 20}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triage_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workouts.paintriageresponse')),
            ],
            options={
                'db_table': 'pain_intervention_steps',
                'ordering': ['triage_response', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='paintriageresponse',
            index=models.Index(fields=['trainee', '-created_at'], name='pain_triage_trainee_740e3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='paininterventionstep',
            constraint=models.UniqueConstraint(fields=('triage_response', 'order'), name='unique_step_order_per_triage'),
        ),
    ]
