# Generated by Django 6.0.1 on 2026-03-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0039_add_pain_triage_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressionprofile',
            name='progression_type',
            field=models.CharField(choices=[('staircase_percent', 'Staircase Percent'), ('rep_staircase', 'Rep Staircase'), ('wave_by_month', 'Wave-by-Month'), ('double_progression', 'Double Progression'), ('linear', 'Linear'), ('dup', 'Daily Undulating'), ('wup', 'Weekly Undulating'), ('block', 'Block Periodization'), ('concurrent', 'Concurrent'), ('conjugate', 'Conjugate (ME/DE/RE)')], max_length=30),
        ),
    ]
