# Generated by Django 6.0.1 on 2026-03-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0040_add_periodization_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='build_mode',
            field=models.CharField(blank=True, choices=[('quick', 'Quick Build'), ('advanced', 'Advanced Builder'), ('curated', 'AI Curated')], help_text='How this plan was built. Null for legacy/manual plans.', max_length=20, null=True),
        ),
    ]
