# Generated by Django 6.0.1 on 2026-03-23 04:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0041_add_curated_build_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fat_source_type',
            field=models.CharField(choices=[('added_fat_source', 'Added Fat (oils, butter, dressings)'), ('protein_fat_source', 'Protein Fat (comes with protein, e.g. salmon, eggs)'), ('mixed', 'Mixed (counts normally)')], default='mixed', help_text="How this food's fat should be classified for Added-Fats-Only mode. added_fat_source: oils, butter, dressings — always counted. protein_fat_source: fat inherent in protein — can be ignored in added-fats mode. mixed: counts normally in both modes.", max_length=25),
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('items', models.JSONField(default=list, help_text='List of food entries: [{food_item_id, name, quantity, unit, protein, carbs, fat, calories}]')),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('prep_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredients', models.JSONField(default=list, help_text='List of ingredients: [{food_item_id, name, quantity, unit, protein, carbs, fat, calories}]')),
                ('steps', models.JSONField(default=list, help_text='Ordered list of preparation steps: [str, ...]')),
                ('calories_per_serving', models.PositiveIntegerField(default=0)),
                ('protein_per_serving', models.FloatField(default=0)),
                ('carbs_per_serving', models.FloatField(default=0)),
                ('fat_per_serving', models.FloatField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyNutritionCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(help_text='Monday of the check-in week.')),
                ('weight_avg_kg', models.FloatField(blank=True, help_text='Average daily weight for the week (kg).', null=True)),
                ('waist_cm', models.FloatField(blank=True, help_text='Optional weekly waist measurement (cm).', null=True)),
                ('adherence_pct', models.FloatField(default=0, help_text='Percent of meals logged vs planned (0-100).')),
                ('completeness_score', models.FloatField(default=0, help_text='How fully they tracked each day (0-100).')),
                ('missed_days', models.PositiveSmallIntegerField(default=0)),
                ('reason_codes', models.JSONField(default=list, help_text='Reasons for missed days: travel, stress, time, etc.')),
                ('hunger', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fatigue', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('digestion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('decision', models.JSONField(default=dict, help_text="What the reactive engine decided: {action: 'adjust_calories', delta_kcal: -200, new_calories: 2100, ...}")),
                ('decision_why', models.TextField(blank=True, default='', help_text='One-sentence human-readable explanation.')),
                ('undo_payload', models.JSONField(default=dict, help_text='Previous state for undo: {old_calories, old_carbs, old_fat}.')),
                ('decision_applied', models.BooleanField(default=False, help_text='Whether the decision was auto-applied or awaiting trainer approval.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_nutrition_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_nutrition_checkins',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['trainee', '-week_start'], name='weekly_nutr_trainee_473686_idx')],
                'constraints': [models.UniqueConstraint(fields=('trainee', 'week_start'), name='unique_weekly_checkin_per_trainee')],
            },
        ),
    ]
