# Generated by Django 6.0.1 on 2026-03-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0042_add_nutrition_spec_v12_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration_bias',
            field=models.CharField(blank=True, choices=[('very_short', 'Very Short Alactic'), ('short', 'Short Set'), ('moderate', 'Moderate Set'), ('extended_tut', 'Extended Time-Under-Tension'), ('timed', 'Timed Interval'), ('continuous', 'Continuous Aerobic'), ('density', 'Density Block')], default='', help_text='Typical set duration category.', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='load_source',
            field=models.CharField(blank=True, choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('cable', 'Cable'), ('machine', 'Machine'), ('band', 'Band'), ('sled', 'Sled / Drag Load'), ('med_ball', 'Med-Ball / Throw Object')], default='', help_text='Primary loading implement for this exercise.', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='support_bias',
            field=models.CharField(blank=True, choices=[('free_standing', 'Free-Standing / Unsupported'), ('hand_supported', 'Hand-Supported'), ('bench_supported', 'Bench-Supported'), ('machine_guided', 'Machine-Guided'), ('cable', 'Cable Line-Supported'), ('assisted', 'Assisted Bodyweight')], default='', help_text='Level of external support or stability assistance.', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='velocity_bias',
            field=models.CharField(blank=True, choices=[('static', 'Static / Isometric'), ('very_slow', 'Very Slow Controlled'), ('controlled', 'Controlled Moderate'), ('normal', 'Normal Rhythmic'), ('explosive', 'Explosive Intent'), ('ballistic', 'Ballistic'), ('reactive', 'Reactive / Elastic')], default='', help_text='Intended movement speed for this exercise.', max_length=20),
        ),
        migrations.AddField(
            model_name='planslot',
            name='coach_locked_swaps',
            field=models.JSONField(blank=True, default=list, help_text='Trainer-approved exercise IDs for this slot. If non-empty, only these appear in Coach-Locked tab.'),
        ),
    ]
