# Generated by Django 6.0.1 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0043_add_exercise_decision_tags_and_coach_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='planslot',
            name='intensity_target_type',
            field=models.CharField(choices=[('fixed_load', 'Fixed Load'), ('load_range', 'Load Range'), ('percent_tm', 'Percent of Training Max'), ('rpe_target', 'RPE Target'), ('rir_target', 'RIR Target'), ('pain_cap', 'Pain Cap'), ('velocity_cutoff', 'Velocity Cutoff'), ('quality_cap', 'Quality Cap')], default='percent_tm', help_text='How intensity is prescribed for this slot.', max_length=20),
        ),
        migrations.AddField(
            model_name='planslot',
            name='intensity_target_value',
            field=models.JSONField(blank=True, default=dict, help_text='Target-type-specific value. Examples: {pct: 80} for percent_tm, {rpe: 8} for rpe_target, {rir: 2} for rir_target, {velocity_mps: 0.5} for velocity_cutoff.'),
        ),
    ]
