# Generated by Django 6.0.1 on 2026-03-24 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0044_add_autoregulation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list, help_text='List of available items: [{name, category, quantity_estimate}]')),
                ('photo_url', models.URLField(blank=True, default='', help_text='URL of the uploaded pantry/fridge photo.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
