# Generated by Django 6.0.1 on 2026-03-24 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_edited_at_is_deleted_to_message'),
        ('workouts', '0045_add_inventory_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMessageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_submission_id', models.UUIDField(blank=True, null=True)),
                ('referenced_object_type', models.CharField(blank=True, choices=[('plan', 'Training Plan'), ('session', 'Session'), ('exercise', 'Exercise'), ('meal_plan', 'Meal Plan'), ('checkin', 'Check-In'), ('support', 'Support Request')], default='', max_length=20)),
                ('referenced_object_id', models.CharField(blank=True, default='', max_length=255)),
                ('capture_mode', models.CharField(choices=[('screen_only', 'Screen Only'), ('front_only', 'Front Camera Only'), ('rear_only', 'Rear Camera Only'), ('screen_plus_front', 'Screen + Front Camera PiP'), ('screen_plus_rear', 'Screen + Rear Camera PiP')], default='front_only', max_length=20)),
                ('camera_layout', models.JSONField(blank=True, default=dict, help_text="Camera bubble config: {position: 'bottom_right', size: 120, minimized: false}")),
                ('screen_route_context', models.JSONField(blank=True, default=dict, help_text='Which screen was being shown: {route, nested_object_ids, app_version}')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_upload_uri', models.URLField(blank=True, default='', max_length=500)),
                ('processed_stream_uri', models.URLField(blank=True, default='', max_length=500)),
                ('thumbnail_uri', models.URLField(blank=True, default='', max_length=500)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('transcript_confidence', models.FloatField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('generating_thumbnail', 'Generating Thumbnail'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=25)),
                ('error_state', models.TextField(blank=True, default='')),
                ('visibility_scope', models.CharField(choices=[('private', 'Private'), ('trainer_only', 'Trainer Only'), ('shared', 'Shared')], default='trainer_only', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_messages_owned', to=settings.AUTH_USER_MODEL)),
                ('thread_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_messages', to='messaging.conversation')),
                ('trainee', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_messages_as_trainee', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_messages_as_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_message_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='video_messa_owner_i_9c59f2_idx'), models.Index(fields=['trainee', '-created_at'], name='video_messa_trainee_72b463_idx'), models.Index(fields=['upload_status'], name='video_messa_upload__43a369_idx')],
            },
        ),
    ]
