# Generated by Django 6.0.1 on 2026-02-14 15:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(help_text='Unique 8-char alphanumeric referral code for sharing', max_length=8, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Commission rate as decimal (0.20 = 20%)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether the ambassador can earn new commissions')),
                ('total_referrals', models.PositiveIntegerField(default=0, help_text='Cached count of total referrals')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached total lifetime earnings', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'AMBASSADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambassador_profiles',
            },
        ),
        migrations.CreateModel(
            name='AmbassadorReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code_used', models.CharField(help_text='The referral code that was used at registration time', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CHURNED', 'Churned')], default='PENDING', max_length=10)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text="Set when trainer's first subscription payment clears", null=True)),
                ('churned_at', models.DateTimeField(blank=True, help_text='Set when trainer cancels subscription', null=True)),
                ('ambassador', models.ForeignKey(limit_choices_to={'role': 'AMBASSADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_referrals', to=settings.AUTH_USER_MODEL)),
                ('ambassador_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='ambassador.ambassadorprofile')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambassador_referrals',
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='AmbassadorCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Snapshot of commission rate at time of charge', max_digits=4)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text="Trainer's subscription payment amount", max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission: base_amount * commission_rate', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('period_start', models.DateField(help_text='Start of the billing period this commission covers')),
                ('period_end', models.DateField(help_text='End of the billing period this commission covers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(limit_choices_to={'role': 'AMBASSADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_commissions', to=settings.AUTH_USER_MODEL)),
                ('ambassador_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='ambassador.ambassadorprofile')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='ambassador.ambassadorreferral')),
            ],
            options={
                'db_table': 'ambassador_commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ambassadorprofile',
            index=models.Index(fields=['referral_code'], name='ambassador__referra_e337ec_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorprofile',
            index=models.Index(fields=['is_active'], name='ambassador__is_acti_461f46_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorreferral',
            index=models.Index(fields=['ambassador', 'status'], name='ambassador__ambassa_1e8d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorreferral',
            index=models.Index(fields=['trainer'], name='ambassador__trainer_3b85c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorreferral',
            index=models.Index(fields=['referral_code_used'], name='ambassador__referra_ae101f_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorreferral',
            index=models.Index(fields=['referred_at'], name='ambassador__referre_c0812a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ambassadorreferral',
            unique_together={('ambassador', 'trainer')},
        ),
        migrations.AddIndex(
            model_name='ambassadorcommission',
            index=models.Index(fields=['ambassador', 'status'], name='ambassador__ambassa_d2401a_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorcommission',
            index=models.Index(fields=['referral'], name='ambassador__referra_791eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorcommission',
            index=models.Index(fields=['period_start', 'period_end'], name='ambassador__period__df2dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='ambassadorcommission',
            index=models.Index(fields=['created_at'], name='ambassador__created_32c042_idx'),
        ),
    ]
