# Generated by Django 6.0.1 on 2026-02-14 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ambassadorreferral',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ambassadorcommission',
            constraint=models.UniqueConstraint(fields=('referral', 'period_start', 'period_end'), name='unique_commission_per_referral_period'),
        ),
        migrations.AddConstraint(
            model_name='ambassadorreferral',
            constraint=models.UniqueConstraint(fields=('ambassador', 'trainer'), name='unique_ambassador_trainer_referral'),
        ),
    ]
