# Generated by Django 6.0.1 on 2026-02-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0002_alter_ambassadorreferral_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorprofile',
            name='referral_code',
            field=models.CharField(help_text='Unique 4-20 char alphanumeric referral code (auto-generated or custom)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ambassadorreferral',
            name='referral_code_used',
            field=models.CharField(help_text='The referral code that was used at registration time', max_length=20),
        ),
    ]
