# Generated by Django 6.0.1 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassador", "0003_alter_ambassadorprofile_referral_code_and_more"),
    ]

    operations = [
        # Create AmbassadorStripeAccount model
        migrations.CreateModel(
            name="AmbassadorStripeAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("details_submitted", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ambassador_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_account",
                        to="ambassador.ambassadorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ambassador_stripe_accounts",
                "indexes": [
                    models.Index(
                        fields=["ambassador_profile"],
                        name="stripe_acct_ambassador_idx",
                    ),
                ],
            },
        ),
        # Create PayoutRecord model
        migrations.CreateModel(
            name="PayoutRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ambassador_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="ambassador.ambassadorprofile",
                    ),
                ),
                (
                    "commissions_included",
                    models.ManyToManyField(
                        blank=True,
                        related_name="payout_records",
                        to="ambassador.ambassadorcommission",
                    ),
                ),
            ],
            options={
                "db_table": "ambassador_payout_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ambassador_profile", "-created_at"],
                        name="payout_ambassador_created_idx",
                    ),
                ],
            },
        ),
    ]
