# Generated by Django 6.0.1 on 2026-03-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassador', '0004_add_stripe_connect_and_payouts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ambassadorstripeaccount',
            new_name='ambassador__ambassa_477587_idx',
            old_name='stripe_acct_ambassador_idx',
        ),
        migrations.RenameIndex(
            model_name='payoutrecord',
            new_name='ambassador__ambassa_8b1a60_idx',
            old_name='payout_ambassador_created_idx',
        ),
    ]
