# Generated by Django 6.0.1 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add content_format to Announcement
        migrations.AddField(
            model_name="announcement",
            name="content_format",
            field=models.CharField(
                choices=[("plain", "Plain"), ("markdown", "Markdown")],
                default="plain",
                max_length=10,
            ),
        ),
        # Add content_format to CommunityPost
        migrations.AddField(
            model_name="communitypost",
            name="content_format",
            field=models.CharField(
                choices=[("plain", "Plain"), ("markdown", "Markdown")],
                default="plain",
                max_length=10,
            ),
        ),
        # Add image to CommunityPost (upload_to uses a string path;
        # the model's lambda for UUID naming still works at runtime)
        migrations.AddField(
            model_name="communitypost",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="community_posts/",
            ),
        ),
        # Create Leaderboard model
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("workout_count", "Workout Count"),
                            ("current_streak", "Current Streak"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        limit_choices_to={"role": "TRAINER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leaderboards",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trainer", "metric_type", "time_period"),
                        name="unique_trainer_metric_period",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["trainer", "is_enabled"],
                        name="leaderboar_trainer_enabled_idx",
                    ),
                ],
            },
        ),
        # Create Comment model
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.communitypost",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "community_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="comment_post_created_idx",
                    ),
                    models.Index(
                        fields=["author"],
                        name="comment_author_idx",
                    ),
                ],
            },
        ),
    ]
