# Generated by Django 6.0.1 on 2026-03-05 23:16

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_migrate_post_images'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='community_b_user_id_876a38_idx',
            old_name='community_b_user_id_f7a8b9_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_post_id_2fbac0_idx',
            old_name='comment_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_author__da8e81_idx',
            old_name='comment_author_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_parent__47f068_idx',
            old_name='community_c_parent__b4c5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='community_p_space_i_77495d_idx',
            old_name='community_p_space_i_a9b8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='leaderboard',
            new_name='leaderboard_trainer_dde979_idx',
            old_name='leaderboar_trainer_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='postimage',
            new_name='community_p_post_id_85ea56_idx',
            old_name='community_p_post_id_e1f2a3_idx',
        ),
        migrations.RenameIndex(
            model_name='space',
            new_name='community_s_trainer_e77bc3_idx',
            old_name='community_s_trainer_7e8a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='spacemembership',
            new_name='community_s_user_id_0ac5f0_idx',
            old_name='community_s_user_id_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='spacemembership',
            new_name='community_s_space_i_1a8b1b_idx',
            old_name='community_s_space_i_d4e5f6_idx',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Deprecated: use PostImage instead. Kept for migration.', null=True, upload_to=community.models._community_post_image_path),
        ),
    ]
