# Generated by Django 6.0.1 on 2026-03-06 00:01

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_community_b_user_id_f7a8b9_idx_community_b_user_id_876a38_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_enabled', models.BooleanField(default=True)),
                ('spaces_enabled', models.BooleanField(default=True)),
                ('courses_enabled', models.BooleanField(default=False)),
                ('events_enabled', models.BooleanField(default=False)),
                ('leaderboard_enabled', models.BooleanField(default=True)),
                ('achievements_enabled', models.BooleanField(default=True)),
                ('bookmarks_enabled', models.BooleanField(default=True)),
                ('trainee_can_post', models.BooleanField(default=True, help_text='If False, only trainer/moderators can post.')),
                ('trainee_can_comment', models.BooleanField(default=True)),
                ('trainee_can_react', models.BooleanField(default=True)),
                ('post_approval_required', models.BooleanField(default=False, help_text='If True, trainee posts require moderator approval.')),
                ('community_name', models.CharField(blank=True, default='', help_text="Custom name for the community (default: trainer's name).", max_length=100)),
                ('welcome_message', models.TextField(blank=True, default='', help_text='Welcome message shown to new members.', max_length=1000)),
                ('community_guidelines', models.TextField(blank=True, default='', help_text='Community rules / guidelines shown to members.', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.OneToOneField(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_config',
            },
        ),
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('event_type', models.CharField(choices=[('live_session', 'Live Session'), ('q_and_a', 'Q&A'), ('workshop', 'Workshop'), ('challenge', 'Challenge'), ('other', 'Other')], default='live_session', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live Now'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('meeting_url', models.URLField(blank=True, default='', help_text='External meeting link (Zoom, Google Meet, etc.)')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Maximum attendees (null = unlimited).', null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.JSONField(blank=True, default=dict, help_text='Recurrence config: {frequency, interval, days_of_week, end_date}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(blank=True, help_text='Optional space this event belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='community.space')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_events',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.communitypost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(help_text='Trainer who owns the community where the report was filed.', limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_content_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('cover_image', models.ImageField(blank=True, upload_to=community.models._course_cover_upload_path)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('drip_enabled', models.BooleanField(default=False, help_text='If True, lessons unlock based on drip_delay_days after enrollment.')),
                ('is_mandatory', models.BooleanField(default=False, help_text='If True, all trainees are auto-enrolled on publish.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(blank=True, help_text='Optional space this course belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='community.space')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_courses',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='community.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_course_enrollments',
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text / Markdown'), ('video', 'Video URL'), ('file', 'File Attachment')], default='text', max_length=20)),
                ('text_content', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='')),
                ('file_attachment', models.FileField(blank=True, upload_to=community.models._lesson_content_upload_path)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('drip_delay_days', models.PositiveIntegerField(default=0, help_text='Days after enrollment before this lesson unlocks (0 = immediate).')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to complete this lesson in minutes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='community.course')),
            ],
            options={
                'db_table': 'community_course_lessons',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')], default='going', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='community.communityevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_event_rsvps',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='community.courseenrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='community.courselesson')),
            ],
            options={
                'db_table': 'community_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warn', 'Warn User'), ('remove_content', 'Remove Content'), ('mute', 'Mute User'), ('ban', 'Ban User'), ('dismiss', 'Dismiss Report')], max_length=20)),
                ('reason', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='community.contentreport')),
            ],
            options={
                'db_table': 'community_moderation_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('is_permanent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the ban expires (null if permanent).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_user_bans',
            },
        ),
        migrations.CreateModel(
            name='AutoModRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('word_filter', 'Word Filter'), ('link_filter', 'Link Filter'), ('spam_detection', 'Spam Detection')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Rule config: {words: [...]} for word_filter, {max_links: N} for link_filter, etc.')),
                ('action', models.CharField(choices=[('flag', 'Flag for Review'), ('remove', 'Auto-Remove'), ('mute_author', 'Mute Author')], default='flag', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, on_delete=django.db.models.deletion.CASCADE, related_name='auto_mod_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_auto_mod_rules',
                'indexes': [models.Index(fields=['trainer', 'is_enabled'], name='community_a_trainer_275da7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['trainer', 'status'], name='community_e_trainer_f95409_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['trainer', 'starts_at'], name='community_e_trainer_f86891_idx'),
        ),
        migrations.AddIndex(
            model_name='communityevent',
            index=models.Index(fields=['space', 'starts_at'], name='community_e_space_i_8505f9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['trainer', 'status'], name='community_c_trainer_b2f099_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['reporter'], name='community_c_reporte_a373a3_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', '-created_at'], name='community_c_status_6dd6de_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['trainer', 'status'], name='community_c_trainer_955d47_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['trainer', 'sort_order'], name='community_c_trainer_97f952_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', '-enrolled_at'], name='community_c_user_id_c663d3_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course'], name='community_c_course__679736_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_enrollment'),
        ),
        migrations.AddIndex(
            model_name='courselesson',
            index=models.Index(fields=['course', 'sort_order'], name='community_c_course__c4d2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'status'], name='community_e_event_i_af831f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['user'], name='community_e_user_id_a1d1eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_rsvp'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'lesson'], name='community_l_enrollm_c46861_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_lesson_progress'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['report'], name='community_m_report__f3cead_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderator'], name='community_m_moderat_bba280_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'trainer', 'is_active'], name='community_u_user_id_db4951_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['trainer', 'is_active'], name='community_u_trainer_70b62a_idx'),
        ),
    ]
