# Generated by Django 6.0.1 on 2026-03-13 20:45

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_add_post_video'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postvideo',
            new_name='community_p_post_id_3dea3e_idx',
            old_name='community_p_post_id_video_sort_idx',
        ),
        migrations.RenameIndex(
            model_name='postvideo',
            new_name='community_p_created_8f0bf9_idx',
            old_name='community_p_video_created_idx',
        ),
        migrations.AddField(
            model_name='communityevent',
            name='location_address',
            field=models.CharField(blank=True, default='', help_text='Physical address for in-person events.', max_length=500),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the event location.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='communityevent',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the event location.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='file',
            field=models.FileField(upload_to=community.models._post_video_upload_path),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=community.models._post_video_thumbnail_path),
        ),
    ]
