# Generated by Django 6.0.1 on 2026-02-19 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='trainee',
            field=models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
