# Generated by Django 6.0.1 on 2026-02-20 00:26

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_trainee_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Optional image attachment (JPEG, PNG, WebP; max 5MB).', null=True, upload_to=messaging.models._message_image_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
