# Generated by Django 6.0.1 on 2026-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name for trainers', max_length=150, null=True),
        ),
    ]
