# Generated by Django 6.0.1 on 2026-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AMBASSADOR', 'Ambassador'), ('TRAINER', 'Trainer'), ('TRAINEE', 'Trainee')], default='TRAINEE', help_text='User role in the platform', max_length=10),
        ),
    ]
