# Generated by Django 6.0.1 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        # Add leaderboard_opt_in to UserProfile
        migrations.AddField(
            model_name="userprofile",
            name="leaderboard_opt_in",
            field=models.BooleanField(
                default=True,
                help_text="Whether this trainee appears on leaderboards",
            ),
        ),
        # Create DeviceToken model
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=512)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device_tokens",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "token"),
                        name="unique_user_device_token",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="device_token_user_active_idx",
                    ),
                ],
            },
        ),
    ]
