# Generated by Django 6.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_device_tokens_and_leaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("pt-br", "Portuguese (Brazil)"),
                ],
                default="en",
                help_text="Preferred UI language",
                max_length=5,
            ),
        ),
    ]
