# Generated by Django 6.0.1 on 2026-03-05 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_workout', models.BooleanField(default=True, help_text='Notify when a trainee completes a workout')),
                ('trainee_weight_checkin', models.BooleanField(default=True, help_text='Notify when a trainee logs a weight check-in')),
                ('trainee_started_workout', models.BooleanField(default=True, help_text='Notify when a trainee starts a workout')),
                ('trainee_finished_workout', models.BooleanField(default=True, help_text='Notify when a trainee finishes a workout')),
                ('churn_alert', models.BooleanField(default=True, help_text='Notify about at-risk trainees')),
                ('trainer_announcement', models.BooleanField(default=True, help_text='Notify on new trainer announcements')),
                ('achievement_earned', models.BooleanField(default=True, help_text='Notify when a new badge is earned')),
                ('new_message', models.BooleanField(default=True, help_text='Notify on new direct messages')),
                ('community_activity', models.BooleanField(default=True, help_text='Notify on community post reactions and comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='device_toke_user_id_e99165_idx',
            old_name='device_token_user_active_idx',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
